<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Mongodb\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class DescribeDBInstanceParametersRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DescribeDBInstanceParametersRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'instance_id' => 'string',
        'parameter_names' => 'string',
        'parameter_role' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'instance_id' => null,
        'parameter_names' => null,
        'parameter_role' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'instance_id' => 'InstanceId',
        'parameter_names' => 'ParameterNames',
        'parameter_role' => 'ParameterRole'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'instance_id' => 'setInstanceId',
        'parameter_names' => 'setParameterNames',
        'parameter_role' => 'setParameterRole'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'instance_id' => 'getInstanceId',
        'parameter_names' => 'getParameterNames',
        'parameter_role' => 'getParameterRole'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const PARAMETER_ROLE_UNKNOWN = 'Unknown';
    const PARAMETER_ROLE_NODE = 'Node';
    const PARAMETER_ROLE_SHARD = 'Shard';
    const PARAMETER_ROLE_CONFIG_SERVER = 'ConfigServer';
    const PARAMETER_ROLE_MONGOS = 'Mongos';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getParameterRoleAllowableValues()
    {
        return [
            self::PARAMETER_ROLE_UNKNOWN,
            self::PARAMETER_ROLE_NODE,
            self::PARAMETER_ROLE_SHARD,
            self::PARAMETER_ROLE_CONFIG_SERVER,
            self::PARAMETER_ROLE_MONGOS,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['instance_id'] = isset($data['instance_id']) ? $data['instance_id'] : null;
        $this->container['parameter_names'] = isset($data['parameter_names']) ? $data['parameter_names'] : null;
        $this->container['parameter_role'] = isset($data['parameter_role']) ? $data['parameter_role'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['instance_id'] === null) {
            $invalidProperties[] = "'instance_id' can't be null";
        }
        $allowedValues = $this->getParameterRoleAllowableValues();
        if (!is_null($this->container['parameter_role']) && !in_array($this->container['parameter_role'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'parameter_role', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets instance_id
     *
     * @return string
     */
    public function getInstanceId()
    {
        return $this->container['instance_id'];
    }

    /**
     * Sets instance_id
     *
     * @param string $instance_id instance_id
     *
     * @return $this
     */
    public function setInstanceId($instance_id)
    {
        $this->container['instance_id'] = $instance_id;

        return $this;
    }

    /**
     * Gets parameter_names
     *
     * @return string
     */
    public function getParameterNames()
    {
        return $this->container['parameter_names'];
    }

    /**
     * Sets parameter_names
     *
     * @param string $parameter_names parameter_names
     *
     * @return $this
     */
    public function setParameterNames($parameter_names)
    {
        $this->container['parameter_names'] = $parameter_names;

        return $this;
    }

    /**
     * Gets parameter_role
     *
     * @return string
     */
    public function getParameterRole()
    {
        return $this->container['parameter_role'];
    }

    /**
     * Sets parameter_role
     *
     * @param string $parameter_role parameter_role
     *
     * @return $this
     */
    public function setParameterRole($parameter_role)
    {
        $allowedValues = $this->getParameterRoleAllowableValues();
        if (!is_null($parameter_role) && !in_array($parameter_role, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'parameter_role', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['parameter_role'] = $parameter_role;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

