<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Mongodb\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class DescribeBackupsRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DescribeBackupsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'backup_object' => 'string',
        'backup_status' => 'string',
        'backup_type' => 'string',
        'end_time' => 'string',
        'instance_id' => 'string',
        'page_number' => 'int',
        'page_size' => 'int',
        'start_time' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'backup_object' => null,
        'backup_status' => null,
        'backup_type' => null,
        'end_time' => null,
        'instance_id' => null,
        'page_number' => 'int32',
        'page_size' => 'int32',
        'start_time' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'backup_object' => 'BackupObject',
        'backup_status' => 'BackupStatus',
        'backup_type' => 'BackupType',
        'end_time' => 'EndTime',
        'instance_id' => 'InstanceId',
        'page_number' => 'PageNumber',
        'page_size' => 'PageSize',
        'start_time' => 'StartTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'backup_object' => 'setBackupObject',
        'backup_status' => 'setBackupStatus',
        'backup_type' => 'setBackupType',
        'end_time' => 'setEndTime',
        'instance_id' => 'setInstanceId',
        'page_number' => 'setPageNumber',
        'page_size' => 'setPageSize',
        'start_time' => 'setStartTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'backup_object' => 'getBackupObject',
        'backup_status' => 'getBackupStatus',
        'backup_type' => 'getBackupType',
        'end_time' => 'getEndTime',
        'instance_id' => 'getInstanceId',
        'page_number' => 'getPageNumber',
        'page_size' => 'getPageSize',
        'start_time' => 'getStartTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const BACKUP_OBJECT_DATA = 'Data';
    const BACKUP_OBJECT_LOG = 'Log';
    const BACKUP_STATUS_SUCCESS = 'Success';
    const BACKUP_STATUS_FAILED = 'Failed';
    const BACKUP_STATUS_RUNNING = 'Running';
    const BACKUP_TYPE_LOGICAL = 'Logical';
    const BACKUP_TYPE_PHYSICAL = 'Physical';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBackupObjectAllowableValues()
    {
        return [
            self::BACKUP_OBJECT_DATA,
            self::BACKUP_OBJECT_LOG,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBackupStatusAllowableValues()
    {
        return [
            self::BACKUP_STATUS_SUCCESS,
            self::BACKUP_STATUS_FAILED,
            self::BACKUP_STATUS_RUNNING,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBackupTypeAllowableValues()
    {
        return [
            self::BACKUP_TYPE_LOGICAL,
            self::BACKUP_TYPE_PHYSICAL,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['backup_object'] = isset($data['backup_object']) ? $data['backup_object'] : null;
        $this->container['backup_status'] = isset($data['backup_status']) ? $data['backup_status'] : null;
        $this->container['backup_type'] = isset($data['backup_type']) ? $data['backup_type'] : null;
        $this->container['end_time'] = isset($data['end_time']) ? $data['end_time'] : null;
        $this->container['instance_id'] = isset($data['instance_id']) ? $data['instance_id'] : null;
        $this->container['page_number'] = isset($data['page_number']) ? $data['page_number'] : null;
        $this->container['page_size'] = isset($data['page_size']) ? $data['page_size'] : null;
        $this->container['start_time'] = isset($data['start_time']) ? $data['start_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getBackupObjectAllowableValues();
        if (!is_null($this->container['backup_object']) && !in_array($this->container['backup_object'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'backup_object', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getBackupStatusAllowableValues();
        if (!is_null($this->container['backup_status']) && !in_array($this->container['backup_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'backup_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getBackupTypeAllowableValues();
        if (!is_null($this->container['backup_type']) && !in_array($this->container['backup_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'backup_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['instance_id'] === null) {
            $invalidProperties[] = "'instance_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets backup_object
     *
     * @return string
     */
    public function getBackupObject()
    {
        return $this->container['backup_object'];
    }

    /**
     * Sets backup_object
     *
     * @param string $backup_object backup_object
     *
     * @return $this
     */
    public function setBackupObject($backup_object)
    {
        $allowedValues = $this->getBackupObjectAllowableValues();
        if (!is_null($backup_object) && !in_array($backup_object, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'backup_object', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['backup_object'] = $backup_object;

        return $this;
    }

    /**
     * Gets backup_status
     *
     * @return string
     */
    public function getBackupStatus()
    {
        return $this->container['backup_status'];
    }

    /**
     * Sets backup_status
     *
     * @param string $backup_status backup_status
     *
     * @return $this
     */
    public function setBackupStatus($backup_status)
    {
        $allowedValues = $this->getBackupStatusAllowableValues();
        if (!is_null($backup_status) && !in_array($backup_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'backup_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['backup_status'] = $backup_status;

        return $this;
    }

    /**
     * Gets backup_type
     *
     * @return string
     */
    public function getBackupType()
    {
        return $this->container['backup_type'];
    }

    /**
     * Sets backup_type
     *
     * @param string $backup_type backup_type
     *
     * @return $this
     */
    public function setBackupType($backup_type)
    {
        $allowedValues = $this->getBackupTypeAllowableValues();
        if (!is_null($backup_type) && !in_array($backup_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'backup_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['backup_type'] = $backup_type;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return string
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param string $end_time end_time
     *
     * @return $this
     */
    public function setEndTime($end_time)
    {
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets instance_id
     *
     * @return string
     */
    public function getInstanceId()
    {
        return $this->container['instance_id'];
    }

    /**
     * Sets instance_id
     *
     * @param string $instance_id instance_id
     *
     * @return $this
     */
    public function setInstanceId($instance_id)
    {
        $this->container['instance_id'] = $instance_id;

        return $this;
    }

    /**
     * Gets page_number
     *
     * @return int
     */
    public function getPageNumber()
    {
        return $this->container['page_number'];
    }

    /**
     * Sets page_number
     *
     * @param int $page_number page_number
     *
     * @return $this
     */
    public function setPageNumber($page_number)
    {
        $this->container['page_number'] = $page_number;

        return $this;
    }

    /**
     * Gets page_size
     *
     * @return int
     */
    public function getPageSize()
    {
        return $this->container['page_size'];
    }

    /**
     * Sets page_size
     *
     * @param int $page_size page_size
     *
     * @return $this
     */
    public function setPageSize($page_size)
    {
        $this->container['page_size'] = $page_size;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return string
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param string $start_time start_time
     *
     * @return $this
     */
    public function setStartTime($start_time)
    {
        $this->container['start_time'] = $start_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

