<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Mongodb\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class ModifyDBInstanceBackupPolicyRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ModifyDBInstanceBackupPolicyRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'data_backup_retention_day' => 'int',
        'data_full_backup_periods' => 'string[]',
        'data_full_backup_time' => 'string',
        'instance_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'data_backup_retention_day' => 'int32',
        'data_full_backup_periods' => null,
        'data_full_backup_time' => null,
        'instance_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'data_backup_retention_day' => 'DataBackupRetentionDay',
        'data_full_backup_periods' => 'DataFullBackupPeriods',
        'data_full_backup_time' => 'DataFullBackupTime',
        'instance_id' => 'InstanceId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'data_backup_retention_day' => 'setDataBackupRetentionDay',
        'data_full_backup_periods' => 'setDataFullBackupPeriods',
        'data_full_backup_time' => 'setDataFullBackupTime',
        'instance_id' => 'setInstanceId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'data_backup_retention_day' => 'getDataBackupRetentionDay',
        'data_full_backup_periods' => 'getDataFullBackupPeriods',
        'data_full_backup_time' => 'getDataFullBackupTime',
        'instance_id' => 'getInstanceId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['data_backup_retention_day'] = isset($data['data_backup_retention_day']) ? $data['data_backup_retention_day'] : null;
        $this->container['data_full_backup_periods'] = isset($data['data_full_backup_periods']) ? $data['data_full_backup_periods'] : null;
        $this->container['data_full_backup_time'] = isset($data['data_full_backup_time']) ? $data['data_full_backup_time'] : null;
        $this->container['instance_id'] = isset($data['instance_id']) ? $data['instance_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['instance_id'] === null) {
            $invalidProperties[] = "'instance_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets data_backup_retention_day
     *
     * @return int
     */
    public function getDataBackupRetentionDay()
    {
        return $this->container['data_backup_retention_day'];
    }

    /**
     * Sets data_backup_retention_day
     *
     * @param int $data_backup_retention_day data_backup_retention_day
     *
     * @return $this
     */
    public function setDataBackupRetentionDay($data_backup_retention_day)
    {
        $this->container['data_backup_retention_day'] = $data_backup_retention_day;

        return $this;
    }

    /**
     * Gets data_full_backup_periods
     *
     * @return string[]
     */
    public function getDataFullBackupPeriods()
    {
        return $this->container['data_full_backup_periods'];
    }

    /**
     * Sets data_full_backup_periods
     *
     * @param string[] $data_full_backup_periods data_full_backup_periods
     *
     * @return $this
     */
    public function setDataFullBackupPeriods($data_full_backup_periods)
    {
        $this->container['data_full_backup_periods'] = $data_full_backup_periods;

        return $this;
    }

    /**
     * Gets data_full_backup_time
     *
     * @return string
     */
    public function getDataFullBackupTime()
    {
        return $this->container['data_full_backup_time'];
    }

    /**
     * Sets data_full_backup_time
     *
     * @param string $data_full_backup_time data_full_backup_time
     *
     * @return $this
     */
    public function setDataFullBackupTime($data_full_backup_time)
    {
        $this->container['data_full_backup_time'] = $data_full_backup_time;

        return $this;
    }

    /**
     * Gets instance_id
     *
     * @return string
     */
    public function getInstanceId()
    {
        return $this->container['instance_id'];
    }

    /**
     * Sets instance_id
     *
     * @param string $instance_id instance_id
     *
     * @return $this
     */
    public function setInstanceId($instance_id)
    {
        $this->container['instance_id'] = $instance_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

