<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Vpn\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class CreateVpnGatewayRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateVpnGatewayRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'asn' => 'int',
        'bandwidth' => 'int',
        'billing_type' => 'int',
        'client_token' => 'string',
        'description' => 'string',
        'dual_tunnel_enabled' => 'bool',
        'ip_stack_type' => 'string',
        'ip_version' => 'string',
        'ipsec_enabled' => 'bool',
        'period' => 'int',
        'period_unit' => 'string',
        'project_name' => 'string',
        'secondary_subnet_id' => 'string',
        'ssl_enabled' => 'bool',
        'ssl_max_connections' => 'int',
        'subnet_id' => 'string',
        'tags' => '\Byteplus\Vpn\Model\TagForCreateVpnGatewayInput[]',
        'vpc_id' => 'string',
        'vpn_gateway_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'asn' => null,
        'bandwidth' => null,
        'billing_type' => null,
        'client_token' => null,
        'description' => null,
        'dual_tunnel_enabled' => null,
        'ip_stack_type' => null,
        'ip_version' => null,
        'ipsec_enabled' => null,
        'period' => null,
        'period_unit' => null,
        'project_name' => null,
        'secondary_subnet_id' => null,
        'ssl_enabled' => null,
        'ssl_max_connections' => null,
        'subnet_id' => null,
        'tags' => null,
        'vpc_id' => null,
        'vpn_gateway_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'asn' => 'Asn',
        'bandwidth' => 'Bandwidth',
        'billing_type' => 'BillingType',
        'client_token' => 'ClientToken',
        'description' => 'Description',
        'dual_tunnel_enabled' => 'DualTunnelEnabled',
        'ip_stack_type' => 'IpStackType',
        'ip_version' => 'IpVersion',
        'ipsec_enabled' => 'IpsecEnabled',
        'period' => 'Period',
        'period_unit' => 'PeriodUnit',
        'project_name' => 'ProjectName',
        'secondary_subnet_id' => 'SecondarySubnetId',
        'ssl_enabled' => 'SslEnabled',
        'ssl_max_connections' => 'SslMaxConnections',
        'subnet_id' => 'SubnetId',
        'tags' => 'Tags',
        'vpc_id' => 'VpcId',
        'vpn_gateway_name' => 'VpnGatewayName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'asn' => 'setAsn',
        'bandwidth' => 'setBandwidth',
        'billing_type' => 'setBillingType',
        'client_token' => 'setClientToken',
        'description' => 'setDescription',
        'dual_tunnel_enabled' => 'setDualTunnelEnabled',
        'ip_stack_type' => 'setIpStackType',
        'ip_version' => 'setIpVersion',
        'ipsec_enabled' => 'setIpsecEnabled',
        'period' => 'setPeriod',
        'period_unit' => 'setPeriodUnit',
        'project_name' => 'setProjectName',
        'secondary_subnet_id' => 'setSecondarySubnetId',
        'ssl_enabled' => 'setSslEnabled',
        'ssl_max_connections' => 'setSslMaxConnections',
        'subnet_id' => 'setSubnetId',
        'tags' => 'setTags',
        'vpc_id' => 'setVpcId',
        'vpn_gateway_name' => 'setVpnGatewayName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'asn' => 'getAsn',
        'bandwidth' => 'getBandwidth',
        'billing_type' => 'getBillingType',
        'client_token' => 'getClientToken',
        'description' => 'getDescription',
        'dual_tunnel_enabled' => 'getDualTunnelEnabled',
        'ip_stack_type' => 'getIpStackType',
        'ip_version' => 'getIpVersion',
        'ipsec_enabled' => 'getIpsecEnabled',
        'period' => 'getPeriod',
        'period_unit' => 'getPeriodUnit',
        'project_name' => 'getProjectName',
        'secondary_subnet_id' => 'getSecondarySubnetId',
        'ssl_enabled' => 'getSslEnabled',
        'ssl_max_connections' => 'getSslMaxConnections',
        'subnet_id' => 'getSubnetId',
        'tags' => 'getTags',
        'vpc_id' => 'getVpcId',
        'vpn_gateway_name' => 'getVpnGatewayName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const PERIOD_UNIT_MONTH = 'Month';
    const PERIOD_UNIT_YEAR = 'Year';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPeriodUnitAllowableValues()
    {
        return [
            self::PERIOD_UNIT_MONTH,
            self::PERIOD_UNIT_YEAR,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['asn'] = isset($data['asn']) ? $data['asn'] : null;
        $this->container['bandwidth'] = isset($data['bandwidth']) ? $data['bandwidth'] : null;
        $this->container['billing_type'] = isset($data['billing_type']) ? $data['billing_type'] : null;
        $this->container['client_token'] = isset($data['client_token']) ? $data['client_token'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['dual_tunnel_enabled'] = isset($data['dual_tunnel_enabled']) ? $data['dual_tunnel_enabled'] : null;
        $this->container['ip_stack_type'] = isset($data['ip_stack_type']) ? $data['ip_stack_type'] : null;
        $this->container['ip_version'] = isset($data['ip_version']) ? $data['ip_version'] : null;
        $this->container['ipsec_enabled'] = isset($data['ipsec_enabled']) ? $data['ipsec_enabled'] : null;
        $this->container['period'] = isset($data['period']) ? $data['period'] : null;
        $this->container['period_unit'] = isset($data['period_unit']) ? $data['period_unit'] : null;
        $this->container['project_name'] = isset($data['project_name']) ? $data['project_name'] : null;
        $this->container['secondary_subnet_id'] = isset($data['secondary_subnet_id']) ? $data['secondary_subnet_id'] : null;
        $this->container['ssl_enabled'] = isset($data['ssl_enabled']) ? $data['ssl_enabled'] : null;
        $this->container['ssl_max_connections'] = isset($data['ssl_max_connections']) ? $data['ssl_max_connections'] : null;
        $this->container['subnet_id'] = isset($data['subnet_id']) ? $data['subnet_id'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['vpc_id'] = isset($data['vpc_id']) ? $data['vpc_id'] : null;
        $this->container['vpn_gateway_name'] = isset($data['vpn_gateway_name']) ? $data['vpn_gateway_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bandwidth'] === null) {
            $invalidProperties[] = "'bandwidth' can't be null";
        }
        $allowedValues = $this->getPeriodUnitAllowableValues();
        if (!is_null($this->container['period_unit']) && !in_array($this->container['period_unit'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'period_unit', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['subnet_id'] === null) {
            $invalidProperties[] = "'subnet_id' can't be null";
        }
        if ($this->container['vpc_id'] === null) {
            $invalidProperties[] = "'vpc_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets asn
     *
     * @return int
     */
    public function getAsn()
    {
        return $this->container['asn'];
    }

    /**
     * Sets asn
     *
     * @param int $asn asn
     *
     * @return $this
     */
    public function setAsn($asn)
    {
        $this->container['asn'] = $asn;

        return $this;
    }

    /**
     * Gets bandwidth
     *
     * @return int
     */
    public function getBandwidth()
    {
        return $this->container['bandwidth'];
    }

    /**
     * Sets bandwidth
     *
     * @param int $bandwidth bandwidth
     *
     * @return $this
     */
    public function setBandwidth($bandwidth)
    {
        $this->container['bandwidth'] = $bandwidth;

        return $this;
    }

    /**
     * Gets billing_type
     *
     * @return int
     */
    public function getBillingType()
    {
        return $this->container['billing_type'];
    }

    /**
     * Sets billing_type
     *
     * @param int $billing_type billing_type
     *
     * @return $this
     */
    public function setBillingType($billing_type)
    {
        $this->container['billing_type'] = $billing_type;

        return $this;
    }

    /**
     * Gets client_token
     *
     * @return string
     */
    public function getClientToken()
    {
        return $this->container['client_token'];
    }

    /**
     * Sets client_token
     *
     * @param string $client_token client_token
     *
     * @return $this
     */
    public function setClientToken($client_token)
    {
        $this->container['client_token'] = $client_token;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets dual_tunnel_enabled
     *
     * @return bool
     */
    public function getDualTunnelEnabled()
    {
        return $this->container['dual_tunnel_enabled'];
    }

    /**
     * Sets dual_tunnel_enabled
     *
     * @param bool $dual_tunnel_enabled dual_tunnel_enabled
     *
     * @return $this
     */
    public function setDualTunnelEnabled($dual_tunnel_enabled)
    {
        $this->container['dual_tunnel_enabled'] = $dual_tunnel_enabled;

        return $this;
    }

    /**
     * Gets ip_stack_type
     *
     * @return string
     */
    public function getIpStackType()
    {
        return $this->container['ip_stack_type'];
    }

    /**
     * Sets ip_stack_type
     *
     * @param string $ip_stack_type ip_stack_type
     *
     * @return $this
     */
    public function setIpStackType($ip_stack_type)
    {
        $this->container['ip_stack_type'] = $ip_stack_type;

        return $this;
    }

    /**
     * Gets ip_version
     *
     * @return string
     */
    public function getIpVersion()
    {
        return $this->container['ip_version'];
    }

    /**
     * Sets ip_version
     *
     * @param string $ip_version ip_version
     *
     * @return $this
     */
    public function setIpVersion($ip_version)
    {
        $this->container['ip_version'] = $ip_version;

        return $this;
    }

    /**
     * Gets ipsec_enabled
     *
     * @return bool
     */
    public function getIpsecEnabled()
    {
        return $this->container['ipsec_enabled'];
    }

    /**
     * Sets ipsec_enabled
     *
     * @param bool $ipsec_enabled ipsec_enabled
     *
     * @return $this
     */
    public function setIpsecEnabled($ipsec_enabled)
    {
        $this->container['ipsec_enabled'] = $ipsec_enabled;

        return $this;
    }

    /**
     * Gets period
     *
     * @return int
     */
    public function getPeriod()
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param int $period period
     *
     * @return $this
     */
    public function setPeriod($period)
    {
        $this->container['period'] = $period;

        return $this;
    }

    /**
     * Gets period_unit
     *
     * @return string
     */
    public function getPeriodUnit()
    {
        return $this->container['period_unit'];
    }

    /**
     * Sets period_unit
     *
     * @param string $period_unit period_unit
     *
     * @return $this
     */
    public function setPeriodUnit($period_unit)
    {
        $allowedValues = $this->getPeriodUnitAllowableValues();
        if (!is_null($period_unit) && !in_array($period_unit, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'period_unit', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['period_unit'] = $period_unit;

        return $this;
    }

    /**
     * Gets project_name
     *
     * @return string
     */
    public function getProjectName()
    {
        return $this->container['project_name'];
    }

    /**
     * Sets project_name
     *
     * @param string $project_name project_name
     *
     * @return $this
     */
    public function setProjectName($project_name)
    {
        $this->container['project_name'] = $project_name;

        return $this;
    }

    /**
     * Gets secondary_subnet_id
     *
     * @return string
     */
    public function getSecondarySubnetId()
    {
        return $this->container['secondary_subnet_id'];
    }

    /**
     * Sets secondary_subnet_id
     *
     * @param string $secondary_subnet_id secondary_subnet_id
     *
     * @return $this
     */
    public function setSecondarySubnetId($secondary_subnet_id)
    {
        $this->container['secondary_subnet_id'] = $secondary_subnet_id;

        return $this;
    }

    /**
     * Gets ssl_enabled
     *
     * @return bool
     */
    public function getSslEnabled()
    {
        return $this->container['ssl_enabled'];
    }

    /**
     * Sets ssl_enabled
     *
     * @param bool $ssl_enabled ssl_enabled
     *
     * @return $this
     */
    public function setSslEnabled($ssl_enabled)
    {
        $this->container['ssl_enabled'] = $ssl_enabled;

        return $this;
    }

    /**
     * Gets ssl_max_connections
     *
     * @return int
     */
    public function getSslMaxConnections()
    {
        return $this->container['ssl_max_connections'];
    }

    /**
     * Sets ssl_max_connections
     *
     * @param int $ssl_max_connections ssl_max_connections
     *
     * @return $this
     */
    public function setSslMaxConnections($ssl_max_connections)
    {
        $this->container['ssl_max_connections'] = $ssl_max_connections;

        return $this;
    }

    /**
     * Gets subnet_id
     *
     * @return string
     */
    public function getSubnetId()
    {
        return $this->container['subnet_id'];
    }

    /**
     * Sets subnet_id
     *
     * @param string $subnet_id subnet_id
     *
     * @return $this
     */
    public function setSubnetId($subnet_id)
    {
        $this->container['subnet_id'] = $subnet_id;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \Byteplus\Vpn\Model\TagForCreateVpnGatewayInput[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \Byteplus\Vpn\Model\TagForCreateVpnGatewayInput[] $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets vpc_id
     *
     * @return string
     */
    public function getVpcId()
    {
        return $this->container['vpc_id'];
    }

    /**
     * Sets vpc_id
     *
     * @param string $vpc_id vpc_id
     *
     * @return $this
     */
    public function setVpcId($vpc_id)
    {
        $this->container['vpc_id'] = $vpc_id;

        return $this;
    }

    /**
     * Gets vpn_gateway_name
     *
     * @return string
     */
    public function getVpnGatewayName()
    {
        return $this->container['vpn_gateway_name'];
    }

    /**
     * Sets vpn_gateway_name
     *
     * @param string $vpn_gateway_name vpn_gateway_name
     *
     * @return $this
     */
    public function setVpnGatewayName($vpn_gateway_name)
    {
        $this->container['vpn_gateway_name'] = $vpn_gateway_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

