<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Vpn\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class CreateVpnConnectionRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateVpnConnectionRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'attach_type' => 'string',
        'bgp_config' => '\Byteplus\Vpn\Model\BgpConfigForCreateVpnConnectionInput',
        'client_token' => 'string',
        'customer_gateway_id' => 'string',
        'description' => 'string',
        'dpd_action' => 'string',
        'enable_tunnels_bgp' => 'bool',
        'ike_config' => '\Byteplus\Vpn\Model\IkeConfigForCreateVpnConnectionInput',
        'ipsec_config' => '\Byteplus\Vpn\Model\IpsecConfigForCreateVpnConnectionInput',
        'local_subnet' => 'string[]',
        'log_enabled' => 'bool',
        'nat_traversal' => 'bool',
        'negotiate_instantly' => 'bool',
        'project_name' => 'string',
        'remote_subnet' => 'string[]',
        'spec' => 'string',
        'tags' => '\Byteplus\Vpn\Model\TagForCreateVpnConnectionInput[]',
        'tunnel_options' => '\Byteplus\Vpn\Model\TunnelOptionForCreateVpnConnectionInput[]',
        'vpn_connection_name' => 'string',
        'vpn_gateway_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'attach_type' => null,
        'bgp_config' => null,
        'client_token' => null,
        'customer_gateway_id' => null,
        'description' => null,
        'dpd_action' => null,
        'enable_tunnels_bgp' => null,
        'ike_config' => null,
        'ipsec_config' => null,
        'local_subnet' => null,
        'log_enabled' => null,
        'nat_traversal' => null,
        'negotiate_instantly' => null,
        'project_name' => null,
        'remote_subnet' => null,
        'spec' => null,
        'tags' => null,
        'tunnel_options' => null,
        'vpn_connection_name' => null,
        'vpn_gateway_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attach_type' => 'AttachType',
        'bgp_config' => 'BgpConfig',
        'client_token' => 'ClientToken',
        'customer_gateway_id' => 'CustomerGatewayId',
        'description' => 'Description',
        'dpd_action' => 'DpdAction',
        'enable_tunnels_bgp' => 'EnableTunnelsBgp',
        'ike_config' => 'IkeConfig',
        'ipsec_config' => 'IpsecConfig',
        'local_subnet' => 'LocalSubnet',
        'log_enabled' => 'LogEnabled',
        'nat_traversal' => 'NatTraversal',
        'negotiate_instantly' => 'NegotiateInstantly',
        'project_name' => 'ProjectName',
        'remote_subnet' => 'RemoteSubnet',
        'spec' => 'Spec',
        'tags' => 'Tags',
        'tunnel_options' => 'TunnelOptions',
        'vpn_connection_name' => 'VpnConnectionName',
        'vpn_gateway_id' => 'VpnGatewayId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attach_type' => 'setAttachType',
        'bgp_config' => 'setBgpConfig',
        'client_token' => 'setClientToken',
        'customer_gateway_id' => 'setCustomerGatewayId',
        'description' => 'setDescription',
        'dpd_action' => 'setDpdAction',
        'enable_tunnels_bgp' => 'setEnableTunnelsBgp',
        'ike_config' => 'setIkeConfig',
        'ipsec_config' => 'setIpsecConfig',
        'local_subnet' => 'setLocalSubnet',
        'log_enabled' => 'setLogEnabled',
        'nat_traversal' => 'setNatTraversal',
        'negotiate_instantly' => 'setNegotiateInstantly',
        'project_name' => 'setProjectName',
        'remote_subnet' => 'setRemoteSubnet',
        'spec' => 'setSpec',
        'tags' => 'setTags',
        'tunnel_options' => 'setTunnelOptions',
        'vpn_connection_name' => 'setVpnConnectionName',
        'vpn_gateway_id' => 'setVpnGatewayId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attach_type' => 'getAttachType',
        'bgp_config' => 'getBgpConfig',
        'client_token' => 'getClientToken',
        'customer_gateway_id' => 'getCustomerGatewayId',
        'description' => 'getDescription',
        'dpd_action' => 'getDpdAction',
        'enable_tunnels_bgp' => 'getEnableTunnelsBgp',
        'ike_config' => 'getIkeConfig',
        'ipsec_config' => 'getIpsecConfig',
        'local_subnet' => 'getLocalSubnet',
        'log_enabled' => 'getLogEnabled',
        'nat_traversal' => 'getNatTraversal',
        'negotiate_instantly' => 'getNegotiateInstantly',
        'project_name' => 'getProjectName',
        'remote_subnet' => 'getRemoteSubnet',
        'spec' => 'getSpec',
        'tags' => 'getTags',
        'tunnel_options' => 'getTunnelOptions',
        'vpn_connection_name' => 'getVpnConnectionName',
        'vpn_gateway_id' => 'getVpnGatewayId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ATTACH_TYPE_VPN_GATEWAY = 'VpnGateway';
    const ATTACH_TYPE_TRANSIT_ROUTER = 'TransitRouter';
    const DPD_ACTION_NONE = 'none';
    const DPD_ACTION_CLEAR = 'clear';
    const DPD_ACTION_HOLD = 'hold';
    const DPD_ACTION_RESTART = 'restart';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAttachTypeAllowableValues()
    {
        return [
            self::ATTACH_TYPE_VPN_GATEWAY,
            self::ATTACH_TYPE_TRANSIT_ROUTER,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDpdActionAllowableValues()
    {
        return [
            self::DPD_ACTION_NONE,
            self::DPD_ACTION_CLEAR,
            self::DPD_ACTION_HOLD,
            self::DPD_ACTION_RESTART,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['attach_type'] = isset($data['attach_type']) ? $data['attach_type'] : null;
        $this->container['bgp_config'] = isset($data['bgp_config']) ? $data['bgp_config'] : null;
        $this->container['client_token'] = isset($data['client_token']) ? $data['client_token'] : null;
        $this->container['customer_gateway_id'] = isset($data['customer_gateway_id']) ? $data['customer_gateway_id'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['dpd_action'] = isset($data['dpd_action']) ? $data['dpd_action'] : null;
        $this->container['enable_tunnels_bgp'] = isset($data['enable_tunnels_bgp']) ? $data['enable_tunnels_bgp'] : null;
        $this->container['ike_config'] = isset($data['ike_config']) ? $data['ike_config'] : null;
        $this->container['ipsec_config'] = isset($data['ipsec_config']) ? $data['ipsec_config'] : null;
        $this->container['local_subnet'] = isset($data['local_subnet']) ? $data['local_subnet'] : null;
        $this->container['log_enabled'] = isset($data['log_enabled']) ? $data['log_enabled'] : null;
        $this->container['nat_traversal'] = isset($data['nat_traversal']) ? $data['nat_traversal'] : null;
        $this->container['negotiate_instantly'] = isset($data['negotiate_instantly']) ? $data['negotiate_instantly'] : null;
        $this->container['project_name'] = isset($data['project_name']) ? $data['project_name'] : null;
        $this->container['remote_subnet'] = isset($data['remote_subnet']) ? $data['remote_subnet'] : null;
        $this->container['spec'] = isset($data['spec']) ? $data['spec'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['tunnel_options'] = isset($data['tunnel_options']) ? $data['tunnel_options'] : null;
        $this->container['vpn_connection_name'] = isset($data['vpn_connection_name']) ? $data['vpn_connection_name'] : null;
        $this->container['vpn_gateway_id'] = isset($data['vpn_gateway_id']) ? $data['vpn_gateway_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAttachTypeAllowableValues();
        if (!is_null($this->container['attach_type']) && !in_array($this->container['attach_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'attach_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDpdActionAllowableValues();
        if (!is_null($this->container['dpd_action']) && !in_array($this->container['dpd_action'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'dpd_action', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attach_type
     *
     * @return string
     */
    public function getAttachType()
    {
        return $this->container['attach_type'];
    }

    /**
     * Sets attach_type
     *
     * @param string $attach_type attach_type
     *
     * @return $this
     */
    public function setAttachType($attach_type)
    {
        $allowedValues = $this->getAttachTypeAllowableValues();
        if (!is_null($attach_type) && !in_array($attach_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'attach_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['attach_type'] = $attach_type;

        return $this;
    }

    /**
     * Gets bgp_config
     *
     * @return \Byteplus\Vpn\Model\BgpConfigForCreateVpnConnectionInput
     */
    public function getBgpConfig()
    {
        return $this->container['bgp_config'];
    }

    /**
     * Sets bgp_config
     *
     * @param \Byteplus\Vpn\Model\BgpConfigForCreateVpnConnectionInput $bgp_config bgp_config
     *
     * @return $this
     */
    public function setBgpConfig($bgp_config)
    {
        $this->container['bgp_config'] = $bgp_config;

        return $this;
    }

    /**
     * Gets client_token
     *
     * @return string
     */
    public function getClientToken()
    {
        return $this->container['client_token'];
    }

    /**
     * Sets client_token
     *
     * @param string $client_token client_token
     *
     * @return $this
     */
    public function setClientToken($client_token)
    {
        $this->container['client_token'] = $client_token;

        return $this;
    }

    /**
     * Gets customer_gateway_id
     *
     * @return string
     */
    public function getCustomerGatewayId()
    {
        return $this->container['customer_gateway_id'];
    }

    /**
     * Sets customer_gateway_id
     *
     * @param string $customer_gateway_id customer_gateway_id
     *
     * @return $this
     */
    public function setCustomerGatewayId($customer_gateway_id)
    {
        $this->container['customer_gateway_id'] = $customer_gateway_id;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets dpd_action
     *
     * @return string
     */
    public function getDpdAction()
    {
        return $this->container['dpd_action'];
    }

    /**
     * Sets dpd_action
     *
     * @param string $dpd_action dpd_action
     *
     * @return $this
     */
    public function setDpdAction($dpd_action)
    {
        $allowedValues = $this->getDpdActionAllowableValues();
        if (!is_null($dpd_action) && !in_array($dpd_action, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'dpd_action', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['dpd_action'] = $dpd_action;

        return $this;
    }

    /**
     * Gets enable_tunnels_bgp
     *
     * @return bool
     */
    public function getEnableTunnelsBgp()
    {
        return $this->container['enable_tunnels_bgp'];
    }

    /**
     * Sets enable_tunnels_bgp
     *
     * @param bool $enable_tunnels_bgp enable_tunnels_bgp
     *
     * @return $this
     */
    public function setEnableTunnelsBgp($enable_tunnels_bgp)
    {
        $this->container['enable_tunnels_bgp'] = $enable_tunnels_bgp;

        return $this;
    }

    /**
     * Gets ike_config
     *
     * @return \Byteplus\Vpn\Model\IkeConfigForCreateVpnConnectionInput
     */
    public function getIkeConfig()
    {
        return $this->container['ike_config'];
    }

    /**
     * Sets ike_config
     *
     * @param \Byteplus\Vpn\Model\IkeConfigForCreateVpnConnectionInput $ike_config ike_config
     *
     * @return $this
     */
    public function setIkeConfig($ike_config)
    {
        $this->container['ike_config'] = $ike_config;

        return $this;
    }

    /**
     * Gets ipsec_config
     *
     * @return \Byteplus\Vpn\Model\IpsecConfigForCreateVpnConnectionInput
     */
    public function getIpsecConfig()
    {
        return $this->container['ipsec_config'];
    }

    /**
     * Sets ipsec_config
     *
     * @param \Byteplus\Vpn\Model\IpsecConfigForCreateVpnConnectionInput $ipsec_config ipsec_config
     *
     * @return $this
     */
    public function setIpsecConfig($ipsec_config)
    {
        $this->container['ipsec_config'] = $ipsec_config;

        return $this;
    }

    /**
     * Gets local_subnet
     *
     * @return string[]
     */
    public function getLocalSubnet()
    {
        return $this->container['local_subnet'];
    }

    /**
     * Sets local_subnet
     *
     * @param string[] $local_subnet local_subnet
     *
     * @return $this
     */
    public function setLocalSubnet($local_subnet)
    {
        $this->container['local_subnet'] = $local_subnet;

        return $this;
    }

    /**
     * Gets log_enabled
     *
     * @return bool
     */
    public function getLogEnabled()
    {
        return $this->container['log_enabled'];
    }

    /**
     * Sets log_enabled
     *
     * @param bool $log_enabled log_enabled
     *
     * @return $this
     */
    public function setLogEnabled($log_enabled)
    {
        $this->container['log_enabled'] = $log_enabled;

        return $this;
    }

    /**
     * Gets nat_traversal
     *
     * @return bool
     */
    public function getNatTraversal()
    {
        return $this->container['nat_traversal'];
    }

    /**
     * Sets nat_traversal
     *
     * @param bool $nat_traversal nat_traversal
     *
     * @return $this
     */
    public function setNatTraversal($nat_traversal)
    {
        $this->container['nat_traversal'] = $nat_traversal;

        return $this;
    }

    /**
     * Gets negotiate_instantly
     *
     * @return bool
     */
    public function getNegotiateInstantly()
    {
        return $this->container['negotiate_instantly'];
    }

    /**
     * Sets negotiate_instantly
     *
     * @param bool $negotiate_instantly negotiate_instantly
     *
     * @return $this
     */
    public function setNegotiateInstantly($negotiate_instantly)
    {
        $this->container['negotiate_instantly'] = $negotiate_instantly;

        return $this;
    }

    /**
     * Gets project_name
     *
     * @return string
     */
    public function getProjectName()
    {
        return $this->container['project_name'];
    }

    /**
     * Sets project_name
     *
     * @param string $project_name project_name
     *
     * @return $this
     */
    public function setProjectName($project_name)
    {
        $this->container['project_name'] = $project_name;

        return $this;
    }

    /**
     * Gets remote_subnet
     *
     * @return string[]
     */
    public function getRemoteSubnet()
    {
        return $this->container['remote_subnet'];
    }

    /**
     * Sets remote_subnet
     *
     * @param string[] $remote_subnet remote_subnet
     *
     * @return $this
     */
    public function setRemoteSubnet($remote_subnet)
    {
        $this->container['remote_subnet'] = $remote_subnet;

        return $this;
    }

    /**
     * Gets spec
     *
     * @return string
     */
    public function getSpec()
    {
        return $this->container['spec'];
    }

    /**
     * Sets spec
     *
     * @param string $spec spec
     *
     * @return $this
     */
    public function setSpec($spec)
    {
        $this->container['spec'] = $spec;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \Byteplus\Vpn\Model\TagForCreateVpnConnectionInput[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \Byteplus\Vpn\Model\TagForCreateVpnConnectionInput[] $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets tunnel_options
     *
     * @return \Byteplus\Vpn\Model\TunnelOptionForCreateVpnConnectionInput[]
     */
    public function getTunnelOptions()
    {
        return $this->container['tunnel_options'];
    }

    /**
     * Sets tunnel_options
     *
     * @param \Byteplus\Vpn\Model\TunnelOptionForCreateVpnConnectionInput[] $tunnel_options tunnel_options
     *
     * @return $this
     */
    public function setTunnelOptions($tunnel_options)
    {
        $this->container['tunnel_options'] = $tunnel_options;

        return $this;
    }

    /**
     * Gets vpn_connection_name
     *
     * @return string
     */
    public function getVpnConnectionName()
    {
        return $this->container['vpn_connection_name'];
    }

    /**
     * Sets vpn_connection_name
     *
     * @param string $vpn_connection_name vpn_connection_name
     *
     * @return $this
     */
    public function setVpnConnectionName($vpn_connection_name)
    {
        $this->container['vpn_connection_name'] = $vpn_connection_name;

        return $this;
    }

    /**
     * Gets vpn_gateway_id
     *
     * @return string
     */
    public function getVpnGatewayId()
    {
        return $this->container['vpn_gateway_id'];
    }

    /**
     * Sets vpn_gateway_id
     *
     * @param string $vpn_gateway_id vpn_gateway_id
     *
     * @return $this
     */
    public function setVpnGatewayId($vpn_gateway_id)
    {
        $this->container['vpn_gateway_id'] = $vpn_gateway_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

