<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Vpn\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class DescribeSslVpnClientCertAttributesResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DescribeSslVpnClientCertAttributesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ca_certificate' => 'string',
        'certificate_status' => 'string',
        'client_certificate' => 'string',
        'client_key' => 'string',
        'creation_time' => 'string',
        'description' => 'string',
        'expired_time' => 'string',
        'open_vpn_client_config' => 'string',
        'request_id' => 'string',
        'ssl_vpn_client_cert_id' => 'string',
        'ssl_vpn_client_cert_name' => 'string',
        'ssl_vpn_server_id' => 'string',
        'status' => 'string',
        'tags' => '\Byteplus\Vpn\Model\TagForDescribeSslVpnClientCertAttributesOutput[]',
        'update_time' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ca_certificate' => null,
        'certificate_status' => null,
        'client_certificate' => null,
        'client_key' => null,
        'creation_time' => null,
        'description' => null,
        'expired_time' => null,
        'open_vpn_client_config' => null,
        'request_id' => null,
        'ssl_vpn_client_cert_id' => null,
        'ssl_vpn_client_cert_name' => null,
        'ssl_vpn_server_id' => null,
        'status' => null,
        'tags' => null,
        'update_time' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ca_certificate' => 'CaCertificate',
        'certificate_status' => 'CertificateStatus',
        'client_certificate' => 'ClientCertificate',
        'client_key' => 'ClientKey',
        'creation_time' => 'CreationTime',
        'description' => 'Description',
        'expired_time' => 'ExpiredTime',
        'open_vpn_client_config' => 'OpenVpnClientConfig',
        'request_id' => 'RequestId',
        'ssl_vpn_client_cert_id' => 'SslVpnClientCertId',
        'ssl_vpn_client_cert_name' => 'SslVpnClientCertName',
        'ssl_vpn_server_id' => 'SslVpnServerId',
        'status' => 'Status',
        'tags' => 'Tags',
        'update_time' => 'UpdateTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ca_certificate' => 'setCaCertificate',
        'certificate_status' => 'setCertificateStatus',
        'client_certificate' => 'setClientCertificate',
        'client_key' => 'setClientKey',
        'creation_time' => 'setCreationTime',
        'description' => 'setDescription',
        'expired_time' => 'setExpiredTime',
        'open_vpn_client_config' => 'setOpenVpnClientConfig',
        'request_id' => 'setRequestId',
        'ssl_vpn_client_cert_id' => 'setSslVpnClientCertId',
        'ssl_vpn_client_cert_name' => 'setSslVpnClientCertName',
        'ssl_vpn_server_id' => 'setSslVpnServerId',
        'status' => 'setStatus',
        'tags' => 'setTags',
        'update_time' => 'setUpdateTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ca_certificate' => 'getCaCertificate',
        'certificate_status' => 'getCertificateStatus',
        'client_certificate' => 'getClientCertificate',
        'client_key' => 'getClientKey',
        'creation_time' => 'getCreationTime',
        'description' => 'getDescription',
        'expired_time' => 'getExpiredTime',
        'open_vpn_client_config' => 'getOpenVpnClientConfig',
        'request_id' => 'getRequestId',
        'ssl_vpn_client_cert_id' => 'getSslVpnClientCertId',
        'ssl_vpn_client_cert_name' => 'getSslVpnClientCertName',
        'ssl_vpn_server_id' => 'getSslVpnServerId',
        'status' => 'getStatus',
        'tags' => 'getTags',
        'update_time' => 'getUpdateTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['ca_certificate'] = isset($data['ca_certificate']) ? $data['ca_certificate'] : null;
        $this->container['certificate_status'] = isset($data['certificate_status']) ? $data['certificate_status'] : null;
        $this->container['client_certificate'] = isset($data['client_certificate']) ? $data['client_certificate'] : null;
        $this->container['client_key'] = isset($data['client_key']) ? $data['client_key'] : null;
        $this->container['creation_time'] = isset($data['creation_time']) ? $data['creation_time'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['expired_time'] = isset($data['expired_time']) ? $data['expired_time'] : null;
        $this->container['open_vpn_client_config'] = isset($data['open_vpn_client_config']) ? $data['open_vpn_client_config'] : null;
        $this->container['request_id'] = isset($data['request_id']) ? $data['request_id'] : null;
        $this->container['ssl_vpn_client_cert_id'] = isset($data['ssl_vpn_client_cert_id']) ? $data['ssl_vpn_client_cert_id'] : null;
        $this->container['ssl_vpn_client_cert_name'] = isset($data['ssl_vpn_client_cert_name']) ? $data['ssl_vpn_client_cert_name'] : null;
        $this->container['ssl_vpn_server_id'] = isset($data['ssl_vpn_server_id']) ? $data['ssl_vpn_server_id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['update_time'] = isset($data['update_time']) ? $data['update_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ca_certificate
     *
     * @return string
     */
    public function getCaCertificate()
    {
        return $this->container['ca_certificate'];
    }

    /**
     * Sets ca_certificate
     *
     * @param string $ca_certificate ca_certificate
     *
     * @return $this
     */
    public function setCaCertificate($ca_certificate)
    {
        $this->container['ca_certificate'] = $ca_certificate;

        return $this;
    }

    /**
     * Gets certificate_status
     *
     * @return string
     */
    public function getCertificateStatus()
    {
        return $this->container['certificate_status'];
    }

    /**
     * Sets certificate_status
     *
     * @param string $certificate_status certificate_status
     *
     * @return $this
     */
    public function setCertificateStatus($certificate_status)
    {
        $this->container['certificate_status'] = $certificate_status;

        return $this;
    }

    /**
     * Gets client_certificate
     *
     * @return string
     */
    public function getClientCertificate()
    {
        return $this->container['client_certificate'];
    }

    /**
     * Sets client_certificate
     *
     * @param string $client_certificate client_certificate
     *
     * @return $this
     */
    public function setClientCertificate($client_certificate)
    {
        $this->container['client_certificate'] = $client_certificate;

        return $this;
    }

    /**
     * Gets client_key
     *
     * @return string
     */
    public function getClientKey()
    {
        return $this->container['client_key'];
    }

    /**
     * Sets client_key
     *
     * @param string $client_key client_key
     *
     * @return $this
     */
    public function setClientKey($client_key)
    {
        $this->container['client_key'] = $client_key;

        return $this;
    }

    /**
     * Gets creation_time
     *
     * @return string
     */
    public function getCreationTime()
    {
        return $this->container['creation_time'];
    }

    /**
     * Sets creation_time
     *
     * @param string $creation_time creation_time
     *
     * @return $this
     */
    public function setCreationTime($creation_time)
    {
        $this->container['creation_time'] = $creation_time;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets expired_time
     *
     * @return string
     */
    public function getExpiredTime()
    {
        return $this->container['expired_time'];
    }

    /**
     * Sets expired_time
     *
     * @param string $expired_time expired_time
     *
     * @return $this
     */
    public function setExpiredTime($expired_time)
    {
        $this->container['expired_time'] = $expired_time;

        return $this;
    }

    /**
     * Gets open_vpn_client_config
     *
     * @return string
     */
    public function getOpenVpnClientConfig()
    {
        return $this->container['open_vpn_client_config'];
    }

    /**
     * Sets open_vpn_client_config
     *
     * @param string $open_vpn_client_config open_vpn_client_config
     *
     * @return $this
     */
    public function setOpenVpnClientConfig($open_vpn_client_config)
    {
        $this->container['open_vpn_client_config'] = $open_vpn_client_config;

        return $this;
    }

    /**
     * Gets request_id
     *
     * @return string
     */
    public function getRequestId()
    {
        return $this->container['request_id'];
    }

    /**
     * Sets request_id
     *
     * @param string $request_id request_id
     *
     * @return $this
     */
    public function setRequestId($request_id)
    {
        $this->container['request_id'] = $request_id;

        return $this;
    }

    /**
     * Gets ssl_vpn_client_cert_id
     *
     * @return string
     */
    public function getSslVpnClientCertId()
    {
        return $this->container['ssl_vpn_client_cert_id'];
    }

    /**
     * Sets ssl_vpn_client_cert_id
     *
     * @param string $ssl_vpn_client_cert_id ssl_vpn_client_cert_id
     *
     * @return $this
     */
    public function setSslVpnClientCertId($ssl_vpn_client_cert_id)
    {
        $this->container['ssl_vpn_client_cert_id'] = $ssl_vpn_client_cert_id;

        return $this;
    }

    /**
     * Gets ssl_vpn_client_cert_name
     *
     * @return string
     */
    public function getSslVpnClientCertName()
    {
        return $this->container['ssl_vpn_client_cert_name'];
    }

    /**
     * Sets ssl_vpn_client_cert_name
     *
     * @param string $ssl_vpn_client_cert_name ssl_vpn_client_cert_name
     *
     * @return $this
     */
    public function setSslVpnClientCertName($ssl_vpn_client_cert_name)
    {
        $this->container['ssl_vpn_client_cert_name'] = $ssl_vpn_client_cert_name;

        return $this;
    }

    /**
     * Gets ssl_vpn_server_id
     *
     * @return string
     */
    public function getSslVpnServerId()
    {
        return $this->container['ssl_vpn_server_id'];
    }

    /**
     * Sets ssl_vpn_server_id
     *
     * @param string $ssl_vpn_server_id ssl_vpn_server_id
     *
     * @return $this
     */
    public function setSslVpnServerId($ssl_vpn_server_id)
    {
        $this->container['ssl_vpn_server_id'] = $ssl_vpn_server_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \Byteplus\Vpn\Model\TagForDescribeSslVpnClientCertAttributesOutput[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \Byteplus\Vpn\Model\TagForDescribeSslVpnClientCertAttributesOutput[] $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets update_time
     *
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->container['update_time'];
    }

    /**
     * Sets update_time
     *
     * @param string $update_time update_time
     *
     * @return $this
     */
    public function setUpdateTime($update_time)
    {
        $this->container['update_time'] = $update_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

