<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Vpn\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class VpnGatewayForDescribeVpnGatewaysBillingOutput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'VpnGatewayForDescribeVpnGatewaysBillingOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'billing_status' => 'int',
        'billing_type' => 'int',
        'expired_time' => 'string',
        'overdue_reclaim_time' => 'string',
        'overdue_time' => 'string',
        'reclaim_time' => 'string',
        'remain_renew_times' => 'int',
        'renew_type' => 'int',
        'vpn_gateway_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'billing_status' => null,
        'billing_type' => null,
        'expired_time' => null,
        'overdue_reclaim_time' => null,
        'overdue_time' => null,
        'reclaim_time' => null,
        'remain_renew_times' => null,
        'renew_type' => null,
        'vpn_gateway_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'billing_status' => 'BillingStatus',
        'billing_type' => 'BillingType',
        'expired_time' => 'ExpiredTime',
        'overdue_reclaim_time' => 'OverdueReclaimTime',
        'overdue_time' => 'OverdueTime',
        'reclaim_time' => 'ReclaimTime',
        'remain_renew_times' => 'RemainRenewTimes',
        'renew_type' => 'RenewType',
        'vpn_gateway_id' => 'VpnGatewayId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'billing_status' => 'setBillingStatus',
        'billing_type' => 'setBillingType',
        'expired_time' => 'setExpiredTime',
        'overdue_reclaim_time' => 'setOverdueReclaimTime',
        'overdue_time' => 'setOverdueTime',
        'reclaim_time' => 'setReclaimTime',
        'remain_renew_times' => 'setRemainRenewTimes',
        'renew_type' => 'setRenewType',
        'vpn_gateway_id' => 'setVpnGatewayId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'billing_status' => 'getBillingStatus',
        'billing_type' => 'getBillingType',
        'expired_time' => 'getExpiredTime',
        'overdue_reclaim_time' => 'getOverdueReclaimTime',
        'overdue_time' => 'getOverdueTime',
        'reclaim_time' => 'getReclaimTime',
        'remain_renew_times' => 'getRemainRenewTimes',
        'renew_type' => 'getRenewType',
        'vpn_gateway_id' => 'getVpnGatewayId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['billing_status'] = isset($data['billing_status']) ? $data['billing_status'] : null;
        $this->container['billing_type'] = isset($data['billing_type']) ? $data['billing_type'] : null;
        $this->container['expired_time'] = isset($data['expired_time']) ? $data['expired_time'] : null;
        $this->container['overdue_reclaim_time'] = isset($data['overdue_reclaim_time']) ? $data['overdue_reclaim_time'] : null;
        $this->container['overdue_time'] = isset($data['overdue_time']) ? $data['overdue_time'] : null;
        $this->container['reclaim_time'] = isset($data['reclaim_time']) ? $data['reclaim_time'] : null;
        $this->container['remain_renew_times'] = isset($data['remain_renew_times']) ? $data['remain_renew_times'] : null;
        $this->container['renew_type'] = isset($data['renew_type']) ? $data['renew_type'] : null;
        $this->container['vpn_gateway_id'] = isset($data['vpn_gateway_id']) ? $data['vpn_gateway_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets billing_status
     *
     * @return int
     */
    public function getBillingStatus()
    {
        return $this->container['billing_status'];
    }

    /**
     * Sets billing_status
     *
     * @param int $billing_status billing_status
     *
     * @return $this
     */
    public function setBillingStatus($billing_status)
    {
        $this->container['billing_status'] = $billing_status;

        return $this;
    }

    /**
     * Gets billing_type
     *
     * @return int
     */
    public function getBillingType()
    {
        return $this->container['billing_type'];
    }

    /**
     * Sets billing_type
     *
     * @param int $billing_type billing_type
     *
     * @return $this
     */
    public function setBillingType($billing_type)
    {
        $this->container['billing_type'] = $billing_type;

        return $this;
    }

    /**
     * Gets expired_time
     *
     * @return string
     */
    public function getExpiredTime()
    {
        return $this->container['expired_time'];
    }

    /**
     * Sets expired_time
     *
     * @param string $expired_time expired_time
     *
     * @return $this
     */
    public function setExpiredTime($expired_time)
    {
        $this->container['expired_time'] = $expired_time;

        return $this;
    }

    /**
     * Gets overdue_reclaim_time
     *
     * @return string
     */
    public function getOverdueReclaimTime()
    {
        return $this->container['overdue_reclaim_time'];
    }

    /**
     * Sets overdue_reclaim_time
     *
     * @param string $overdue_reclaim_time overdue_reclaim_time
     *
     * @return $this
     */
    public function setOverdueReclaimTime($overdue_reclaim_time)
    {
        $this->container['overdue_reclaim_time'] = $overdue_reclaim_time;

        return $this;
    }

    /**
     * Gets overdue_time
     *
     * @return string
     */
    public function getOverdueTime()
    {
        return $this->container['overdue_time'];
    }

    /**
     * Sets overdue_time
     *
     * @param string $overdue_time overdue_time
     *
     * @return $this
     */
    public function setOverdueTime($overdue_time)
    {
        $this->container['overdue_time'] = $overdue_time;

        return $this;
    }

    /**
     * Gets reclaim_time
     *
     * @return string
     */
    public function getReclaimTime()
    {
        return $this->container['reclaim_time'];
    }

    /**
     * Sets reclaim_time
     *
     * @param string $reclaim_time reclaim_time
     *
     * @return $this
     */
    public function setReclaimTime($reclaim_time)
    {
        $this->container['reclaim_time'] = $reclaim_time;

        return $this;
    }

    /**
     * Gets remain_renew_times
     *
     * @return int
     */
    public function getRemainRenewTimes()
    {
        return $this->container['remain_renew_times'];
    }

    /**
     * Sets remain_renew_times
     *
     * @param int $remain_renew_times remain_renew_times
     *
     * @return $this
     */
    public function setRemainRenewTimes($remain_renew_times)
    {
        $this->container['remain_renew_times'] = $remain_renew_times;

        return $this;
    }

    /**
     * Gets renew_type
     *
     * @return int
     */
    public function getRenewType()
    {
        return $this->container['renew_type'];
    }

    /**
     * Sets renew_type
     *
     * @param int $renew_type renew_type
     *
     * @return $this
     */
    public function setRenewType($renew_type)
    {
        $this->container['renew_type'] = $renew_type;

        return $this;
    }

    /**
     * Gets vpn_gateway_id
     *
     * @return string
     */
    public function getVpnGatewayId()
    {
        return $this->container['vpn_gateway_id'];
    }

    /**
     * Sets vpn_gateway_id
     *
     * @param string $vpn_gateway_id vpn_gateway_id
     *
     * @return $this
     */
    public function setVpnGatewayId($vpn_gateway_id)
    {
        $this->container['vpn_gateway_id'] = $vpn_gateway_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

