<?php

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Autoscaling\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Byteplus\Common\ApiException;
use Byteplus\Common\Configuration;
use Byteplus\Common\HeaderSelector;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\Utils;
use Byteplus\Common\ApiClient;

class AUTOSCALINGApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var ApiClient
     */
    protected $apiClient;

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null $config
     * @param HeaderSelector|null $selector
     * @param ApiClient|null $apiClient
     */
    public function __construct(
        $client = null,
        $config = null,
        $selector = null,
        $apiClient = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->apiClient = $apiClient ?: new ApiClient($this->config, $this->client);
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function attachInstances($body = null)
    {
        list($response) = $this->attachInstancesWithHttpInfo($body);
        return $response;
    }

    public function attachInstancesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\AttachInstancesResponse';
        $request = $this->attachInstancesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function attachInstancesAsync($body = null)
    {
        return $this->attachInstancesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function attachInstancesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\AttachInstancesResponse';
        $request = $this->attachInstancesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function attachInstancesRequest($body)
    {
        $resourcePath = '/AttachInstances/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function attachServerGroups($body = null)
    {
        list($response) = $this->attachServerGroupsWithHttpInfo($body);
        return $response;
    }

    public function attachServerGroupsWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\AttachServerGroupsResponse';
        $request = $this->attachServerGroupsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function attachServerGroupsAsync($body = null)
    {
        return $this->attachServerGroupsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function attachServerGroupsAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\AttachServerGroupsResponse';
        $request = $this->attachServerGroupsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function attachServerGroupsRequest($body)
    {
        $resourcePath = '/AttachServerGroups/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function completeLifecycleActivity($body = null)
    {
        list($response) = $this->completeLifecycleActivityWithHttpInfo($body);
        return $response;
    }

    public function completeLifecycleActivityWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CompleteLifecycleActivityResponse';
        $request = $this->completeLifecycleActivityRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function completeLifecycleActivityAsync($body = null)
    {
        return $this->completeLifecycleActivityAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function completeLifecycleActivityAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CompleteLifecycleActivityResponse';
        $request = $this->completeLifecycleActivityRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function completeLifecycleActivityRequest($body)
    {
        $resourcePath = '/CompleteLifecycleActivity/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function createLifecycleHook($body = null)
    {
        list($response) = $this->createLifecycleHookWithHttpInfo($body);
        return $response;
    }

    public function createLifecycleHookWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateLifecycleHookResponse';
        $request = $this->createLifecycleHookRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function createLifecycleHookAsync($body = null)
    {
        return $this->createLifecycleHookAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function createLifecycleHookAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateLifecycleHookResponse';
        $request = $this->createLifecycleHookRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function createLifecycleHookRequest($body)
    {
        $resourcePath = '/CreateLifecycleHook/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function createNotificationConfiguration($body = null)
    {
        list($response) = $this->createNotificationConfigurationWithHttpInfo($body);
        return $response;
    }

    public function createNotificationConfigurationWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateNotificationConfigurationResponse';
        $request = $this->createNotificationConfigurationRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function createNotificationConfigurationAsync($body = null)
    {
        return $this->createNotificationConfigurationAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function createNotificationConfigurationAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateNotificationConfigurationResponse';
        $request = $this->createNotificationConfigurationRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function createNotificationConfigurationRequest($body)
    {
        $resourcePath = '/CreateNotificationConfiguration/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function createScalingConfiguration($body = null)
    {
        list($response) = $this->createScalingConfigurationWithHttpInfo($body);
        return $response;
    }

    public function createScalingConfigurationWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateScalingConfigurationResponse';
        $request = $this->createScalingConfigurationRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function createScalingConfigurationAsync($body = null)
    {
        return $this->createScalingConfigurationAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function createScalingConfigurationAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateScalingConfigurationResponse';
        $request = $this->createScalingConfigurationRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function createScalingConfigurationRequest($body)
    {
        $resourcePath = '/CreateScalingConfiguration/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function createScalingGroup($body = null)
    {
        list($response) = $this->createScalingGroupWithHttpInfo($body);
        return $response;
    }

    public function createScalingGroupWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateScalingGroupResponse';
        $request = $this->createScalingGroupRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function createScalingGroupAsync($body = null)
    {
        return $this->createScalingGroupAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function createScalingGroupAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateScalingGroupResponse';
        $request = $this->createScalingGroupRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function createScalingGroupRequest($body)
    {
        $resourcePath = '/CreateScalingGroup/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function createScalingPolicy($body = null)
    {
        list($response) = $this->createScalingPolicyWithHttpInfo($body);
        return $response;
    }

    public function createScalingPolicyWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateScalingPolicyResponse';
        $request = $this->createScalingPolicyRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function createScalingPolicyAsync($body = null)
    {
        return $this->createScalingPolicyAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function createScalingPolicyAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\CreateScalingPolicyResponse';
        $request = $this->createScalingPolicyRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function createScalingPolicyRequest($body)
    {
        $resourcePath = '/CreateScalingPolicy/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function deleteLifecycleHook($body = null)
    {
        list($response) = $this->deleteLifecycleHookWithHttpInfo($body);
        return $response;
    }

    public function deleteLifecycleHookWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteLifecycleHookResponse';
        $request = $this->deleteLifecycleHookRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function deleteLifecycleHookAsync($body = null)
    {
        return $this->deleteLifecycleHookAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function deleteLifecycleHookAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteLifecycleHookResponse';
        $request = $this->deleteLifecycleHookRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function deleteLifecycleHookRequest($body)
    {
        $resourcePath = '/DeleteLifecycleHook/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function deleteNotificationConfiguration($body = null)
    {
        list($response) = $this->deleteNotificationConfigurationWithHttpInfo($body);
        return $response;
    }

    public function deleteNotificationConfigurationWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteNotificationConfigurationResponse';
        $request = $this->deleteNotificationConfigurationRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function deleteNotificationConfigurationAsync($body = null)
    {
        return $this->deleteNotificationConfigurationAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function deleteNotificationConfigurationAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteNotificationConfigurationResponse';
        $request = $this->deleteNotificationConfigurationRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function deleteNotificationConfigurationRequest($body)
    {
        $resourcePath = '/DeleteNotificationConfiguration/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function deleteScalingConfiguration($body = null)
    {
        list($response) = $this->deleteScalingConfigurationWithHttpInfo($body);
        return $response;
    }

    public function deleteScalingConfigurationWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteScalingConfigurationResponse';
        $request = $this->deleteScalingConfigurationRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function deleteScalingConfigurationAsync($body = null)
    {
        return $this->deleteScalingConfigurationAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function deleteScalingConfigurationAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteScalingConfigurationResponse';
        $request = $this->deleteScalingConfigurationRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function deleteScalingConfigurationRequest($body)
    {
        $resourcePath = '/DeleteScalingConfiguration/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function deleteScalingGroup($body = null)
    {
        list($response) = $this->deleteScalingGroupWithHttpInfo($body);
        return $response;
    }

    public function deleteScalingGroupWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteScalingGroupResponse';
        $request = $this->deleteScalingGroupRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function deleteScalingGroupAsync($body = null)
    {
        return $this->deleteScalingGroupAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function deleteScalingGroupAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteScalingGroupResponse';
        $request = $this->deleteScalingGroupRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function deleteScalingGroupRequest($body)
    {
        $resourcePath = '/DeleteScalingGroup/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function deleteScalingPolicy($body = null)
    {
        list($response) = $this->deleteScalingPolicyWithHttpInfo($body);
        return $response;
    }

    public function deleteScalingPolicyWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteScalingPolicyResponse';
        $request = $this->deleteScalingPolicyRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function deleteScalingPolicyAsync($body = null)
    {
        return $this->deleteScalingPolicyAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function deleteScalingPolicyAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DeleteScalingPolicyResponse';
        $request = $this->deleteScalingPolicyRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function deleteScalingPolicyRequest($body)
    {
        $resourcePath = '/DeleteScalingPolicy/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeLifecycleActivities($body = null)
    {
        list($response) = $this->describeLifecycleActivitiesWithHttpInfo($body);
        return $response;
    }

    public function describeLifecycleActivitiesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeLifecycleActivitiesResponse';
        $request = $this->describeLifecycleActivitiesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeLifecycleActivitiesAsync($body = null)
    {
        return $this->describeLifecycleActivitiesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeLifecycleActivitiesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeLifecycleActivitiesResponse';
        $request = $this->describeLifecycleActivitiesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeLifecycleActivitiesRequest($body)
    {
        $resourcePath = '/DescribeLifecycleActivities/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeLifecycleHooks($body = null)
    {
        list($response) = $this->describeLifecycleHooksWithHttpInfo($body);
        return $response;
    }

    public function describeLifecycleHooksWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeLifecycleHooksResponse';
        $request = $this->describeLifecycleHooksRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeLifecycleHooksAsync($body = null)
    {
        return $this->describeLifecycleHooksAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeLifecycleHooksAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeLifecycleHooksResponse';
        $request = $this->describeLifecycleHooksRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeLifecycleHooksRequest($body)
    {
        $resourcePath = '/DescribeLifecycleHooks/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeNotificationConfigurations($body = null)
    {
        list($response) = $this->describeNotificationConfigurationsWithHttpInfo($body);
        return $response;
    }

    public function describeNotificationConfigurationsWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeNotificationConfigurationsResponse';
        $request = $this->describeNotificationConfigurationsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeNotificationConfigurationsAsync($body = null)
    {
        return $this->describeNotificationConfigurationsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeNotificationConfigurationsAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeNotificationConfigurationsResponse';
        $request = $this->describeNotificationConfigurationsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeNotificationConfigurationsRequest($body)
    {
        $resourcePath = '/DescribeNotificationConfigurations/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeScalingActivities($body = null)
    {
        list($response) = $this->describeScalingActivitiesWithHttpInfo($body);
        return $response;
    }

    public function describeScalingActivitiesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingActivitiesResponse';
        $request = $this->describeScalingActivitiesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeScalingActivitiesAsync($body = null)
    {
        return $this->describeScalingActivitiesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeScalingActivitiesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingActivitiesResponse';
        $request = $this->describeScalingActivitiesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeScalingActivitiesRequest($body)
    {
        $resourcePath = '/DescribeScalingActivities/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeScalingConfigurations($body = null)
    {
        list($response) = $this->describeScalingConfigurationsWithHttpInfo($body);
        return $response;
    }

    public function describeScalingConfigurationsWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingConfigurationsResponse';
        $request = $this->describeScalingConfigurationsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeScalingConfigurationsAsync($body = null)
    {
        return $this->describeScalingConfigurationsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeScalingConfigurationsAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingConfigurationsResponse';
        $request = $this->describeScalingConfigurationsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeScalingConfigurationsRequest($body)
    {
        $resourcePath = '/DescribeScalingConfigurations/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeScalingGroups($body = null)
    {
        list($response) = $this->describeScalingGroupsWithHttpInfo($body);
        return $response;
    }

    public function describeScalingGroupsWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingGroupsResponse';
        $request = $this->describeScalingGroupsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeScalingGroupsAsync($body = null)
    {
        return $this->describeScalingGroupsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeScalingGroupsAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingGroupsResponse';
        $request = $this->describeScalingGroupsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeScalingGroupsRequest($body)
    {
        $resourcePath = '/DescribeScalingGroups/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeScalingInstances($body = null)
    {
        list($response) = $this->describeScalingInstancesWithHttpInfo($body);
        return $response;
    }

    public function describeScalingInstancesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingInstancesResponse';
        $request = $this->describeScalingInstancesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeScalingInstancesAsync($body = null)
    {
        return $this->describeScalingInstancesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeScalingInstancesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingInstancesResponse';
        $request = $this->describeScalingInstancesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeScalingInstancesRequest($body)
    {
        $resourcePath = '/DescribeScalingInstances/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeScalingPolicies($body = null)
    {
        list($response) = $this->describeScalingPoliciesWithHttpInfo($body);
        return $response;
    }

    public function describeScalingPoliciesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingPoliciesResponse';
        $request = $this->describeScalingPoliciesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeScalingPoliciesAsync($body = null)
    {
        return $this->describeScalingPoliciesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeScalingPoliciesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DescribeScalingPoliciesResponse';
        $request = $this->describeScalingPoliciesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeScalingPoliciesRequest($body)
    {
        $resourcePath = '/DescribeScalingPolicies/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function detachInstances($body = null)
    {
        list($response) = $this->detachInstancesWithHttpInfo($body);
        return $response;
    }

    public function detachInstancesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DetachInstancesResponse';
        $request = $this->detachInstancesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function detachInstancesAsync($body = null)
    {
        return $this->detachInstancesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function detachInstancesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DetachInstancesResponse';
        $request = $this->detachInstancesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function detachInstancesRequest($body)
    {
        $resourcePath = '/DetachInstances/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function detachServerGroups($body = null)
    {
        list($response) = $this->detachServerGroupsWithHttpInfo($body);
        return $response;
    }

    public function detachServerGroupsWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DetachServerGroupsResponse';
        $request = $this->detachServerGroupsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function detachServerGroupsAsync($body = null)
    {
        return $this->detachServerGroupsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function detachServerGroupsAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DetachServerGroupsResponse';
        $request = $this->detachServerGroupsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function detachServerGroupsRequest($body)
    {
        $resourcePath = '/DetachServerGroups/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function disableScalingGroup($body = null)
    {
        list($response) = $this->disableScalingGroupWithHttpInfo($body);
        return $response;
    }

    public function disableScalingGroupWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DisableScalingGroupResponse';
        $request = $this->disableScalingGroupRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function disableScalingGroupAsync($body = null)
    {
        return $this->disableScalingGroupAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function disableScalingGroupAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DisableScalingGroupResponse';
        $request = $this->disableScalingGroupRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function disableScalingGroupRequest($body)
    {
        $resourcePath = '/DisableScalingGroup/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function disableScalingPolicy($body = null)
    {
        list($response) = $this->disableScalingPolicyWithHttpInfo($body);
        return $response;
    }

    public function disableScalingPolicyWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DisableScalingPolicyResponse';
        $request = $this->disableScalingPolicyRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function disableScalingPolicyAsync($body = null)
    {
        return $this->disableScalingPolicyAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function disableScalingPolicyAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\DisableScalingPolicyResponse';
        $request = $this->disableScalingPolicyRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function disableScalingPolicyRequest($body)
    {
        $resourcePath = '/DisableScalingPolicy/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function enableScalingConfiguration($body = null)
    {
        list($response) = $this->enableScalingConfigurationWithHttpInfo($body);
        return $response;
    }

    public function enableScalingConfigurationWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\EnableScalingConfigurationResponse';
        $request = $this->enableScalingConfigurationRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function enableScalingConfigurationAsync($body = null)
    {
        return $this->enableScalingConfigurationAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function enableScalingConfigurationAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\EnableScalingConfigurationResponse';
        $request = $this->enableScalingConfigurationRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function enableScalingConfigurationRequest($body)
    {
        $resourcePath = '/EnableScalingConfiguration/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function enableScalingGroup($body = null)
    {
        list($response) = $this->enableScalingGroupWithHttpInfo($body);
        return $response;
    }

    public function enableScalingGroupWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\EnableScalingGroupResponse';
        $request = $this->enableScalingGroupRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function enableScalingGroupAsync($body = null)
    {
        return $this->enableScalingGroupAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function enableScalingGroupAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\EnableScalingGroupResponse';
        $request = $this->enableScalingGroupRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function enableScalingGroupRequest($body)
    {
        $resourcePath = '/EnableScalingGroup/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function enableScalingPolicy($body = null)
    {
        list($response) = $this->enableScalingPolicyWithHttpInfo($body);
        return $response;
    }

    public function enableScalingPolicyWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\EnableScalingPolicyResponse';
        $request = $this->enableScalingPolicyRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function enableScalingPolicyAsync($body = null)
    {
        return $this->enableScalingPolicyAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function enableScalingPolicyAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\EnableScalingPolicyResponse';
        $request = $this->enableScalingPolicyRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function enableScalingPolicyRequest($body)
    {
        $resourcePath = '/EnableScalingPolicy/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function enterStandby($body = null)
    {
        list($response) = $this->enterStandbyWithHttpInfo($body);
        return $response;
    }

    public function enterStandbyWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\EnterStandbyResponse';
        $request = $this->enterStandbyRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function enterStandbyAsync($body = null)
    {
        return $this->enterStandbyAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function enterStandbyAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\EnterStandbyResponse';
        $request = $this->enterStandbyRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function enterStandbyRequest($body)
    {
        $resourcePath = '/EnterStandby/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function exitStandby($body = null)
    {
        list($response) = $this->exitStandbyWithHttpInfo($body);
        return $response;
    }

    public function exitStandbyWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ExitStandbyResponse';
        $request = $this->exitStandbyRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function exitStandbyAsync($body = null)
    {
        return $this->exitStandbyAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function exitStandbyAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ExitStandbyResponse';
        $request = $this->exitStandbyRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function exitStandbyRequest($body)
    {
        $resourcePath = '/ExitStandby/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listTagResources($body = null)
    {
        list($response) = $this->listTagResourcesWithHttpInfo($body);
        return $response;
    }

    public function listTagResourcesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ListTagResourcesResponse';
        $request = $this->listTagResourcesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listTagResourcesAsync($body = null)
    {
        return $this->listTagResourcesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listTagResourcesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ListTagResourcesResponse';
        $request = $this->listTagResourcesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listTagResourcesRequest($body)
    {
        $resourcePath = '/ListTagResources/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function modifyLifecycleHook($body = null)
    {
        list($response) = $this->modifyLifecycleHookWithHttpInfo($body);
        return $response;
    }

    public function modifyLifecycleHookWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyLifecycleHookResponse';
        $request = $this->modifyLifecycleHookRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function modifyLifecycleHookAsync($body = null)
    {
        return $this->modifyLifecycleHookAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function modifyLifecycleHookAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyLifecycleHookResponse';
        $request = $this->modifyLifecycleHookRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function modifyLifecycleHookRequest($body)
    {
        $resourcePath = '/ModifyLifecycleHook/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function modifyNotificationConfiguration($body = null)
    {
        list($response) = $this->modifyNotificationConfigurationWithHttpInfo($body);
        return $response;
    }

    public function modifyNotificationConfigurationWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyNotificationConfigurationResponse';
        $request = $this->modifyNotificationConfigurationRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function modifyNotificationConfigurationAsync($body = null)
    {
        return $this->modifyNotificationConfigurationAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function modifyNotificationConfigurationAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyNotificationConfigurationResponse';
        $request = $this->modifyNotificationConfigurationRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function modifyNotificationConfigurationRequest($body)
    {
        $resourcePath = '/ModifyNotificationConfiguration/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function modifyScalingConfiguration($body = null)
    {
        list($response) = $this->modifyScalingConfigurationWithHttpInfo($body);
        return $response;
    }

    public function modifyScalingConfigurationWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyScalingConfigurationResponse';
        $request = $this->modifyScalingConfigurationRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function modifyScalingConfigurationAsync($body = null)
    {
        return $this->modifyScalingConfigurationAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function modifyScalingConfigurationAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyScalingConfigurationResponse';
        $request = $this->modifyScalingConfigurationRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function modifyScalingConfigurationRequest($body)
    {
        $resourcePath = '/ModifyScalingConfiguration/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function modifyScalingGroup($body = null)
    {
        list($response) = $this->modifyScalingGroupWithHttpInfo($body);
        return $response;
    }

    public function modifyScalingGroupWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyScalingGroupResponse';
        $request = $this->modifyScalingGroupRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function modifyScalingGroupAsync($body = null)
    {
        return $this->modifyScalingGroupAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function modifyScalingGroupAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyScalingGroupResponse';
        $request = $this->modifyScalingGroupRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function modifyScalingGroupRequest($body)
    {
        $resourcePath = '/ModifyScalingGroup/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function modifyScalingPolicy($body = null)
    {
        list($response) = $this->modifyScalingPolicyWithHttpInfo($body);
        return $response;
    }

    public function modifyScalingPolicyWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyScalingPolicyResponse';
        $request = $this->modifyScalingPolicyRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function modifyScalingPolicyAsync($body = null)
    {
        return $this->modifyScalingPolicyAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function modifyScalingPolicyAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ModifyScalingPolicyResponse';
        $request = $this->modifyScalingPolicyRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function modifyScalingPolicyRequest($body)
    {
        $resourcePath = '/ModifyScalingPolicy/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function removeInstances($body = null)
    {
        list($response) = $this->removeInstancesWithHttpInfo($body);
        return $response;
    }

    public function removeInstancesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\RemoveInstancesResponse';
        $request = $this->removeInstancesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function removeInstancesAsync($body = null)
    {
        return $this->removeInstancesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function removeInstancesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\RemoveInstancesResponse';
        $request = $this->removeInstancesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function removeInstancesRequest($body)
    {
        $resourcePath = '/RemoveInstances/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function resumeProcesses($body = null)
    {
        list($response) = $this->resumeProcessesWithHttpInfo($body);
        return $response;
    }

    public function resumeProcessesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ResumeProcessesResponse';
        $request = $this->resumeProcessesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function resumeProcessesAsync($body = null)
    {
        return $this->resumeProcessesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function resumeProcessesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\ResumeProcessesResponse';
        $request = $this->resumeProcessesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function resumeProcessesRequest($body)
    {
        $resourcePath = '/ResumeProcesses/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function setInstancesProtection($body = null)
    {
        list($response) = $this->setInstancesProtectionWithHttpInfo($body);
        return $response;
    }

    public function setInstancesProtectionWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\SetInstancesProtectionResponse';
        $request = $this->setInstancesProtectionRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function setInstancesProtectionAsync($body = null)
    {
        return $this->setInstancesProtectionAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function setInstancesProtectionAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\SetInstancesProtectionResponse';
        $request = $this->setInstancesProtectionRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function setInstancesProtectionRequest($body)
    {
        $resourcePath = '/SetInstancesProtection/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function suspendProcesses($body = null)
    {
        list($response) = $this->suspendProcessesWithHttpInfo($body);
        return $response;
    }

    public function suspendProcessesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\SuspendProcessesResponse';
        $request = $this->suspendProcessesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function suspendProcessesAsync($body = null)
    {
        return $this->suspendProcessesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function suspendProcessesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\SuspendProcessesResponse';
        $request = $this->suspendProcessesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function suspendProcessesRequest($body)
    {
        $resourcePath = '/SuspendProcesses/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function tagResources($body = null)
    {
        list($response) = $this->tagResourcesWithHttpInfo($body);
        return $response;
    }

    public function tagResourcesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\TagResourcesResponse';
        $request = $this->tagResourcesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function tagResourcesAsync($body = null)
    {
        return $this->tagResourcesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function tagResourcesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\TagResourcesResponse';
        $request = $this->tagResourcesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function tagResourcesRequest($body)
    {
        $resourcePath = '/TagResources/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function untagResources($body = null)
    {
        list($response) = $this->untagResourcesWithHttpInfo($body);
        return $response;
    }

    public function untagResourcesWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\UntagResourcesResponse';
        $request = $this->untagResourcesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function untagResourcesAsync($body = null)
    {
        return $this->untagResourcesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function untagResourcesAsyncWithHttpInfo($body)
    {
        $returnType = '\Byteplus\Autoscaling\Model\UntagResourcesResponse';
        $request = $this->untagResourcesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function untagResourcesRequest($body)
    {
        $resourcePath = '/UntagResources/2020-01-01/auto_scaling/get/text_plain/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['text/plain']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }


    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
