<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Kickart\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class CreateMediaRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateMediaRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'aspect_ratio' => 'string',
        'description' => 'string',
        'folder_id' => 'int',
        'media_extension' => 'string',
        'not_save_to_asset' => 'bool',
        'resource_item' => 'string',
        'resource_type' => 'string',
        'tags' => 'string[]',
        'team_space_id' => 'int',
        'title' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'aspect_ratio' => null,
        'description' => null,
        'folder_id' => 'int64',
        'media_extension' => null,
        'not_save_to_asset' => null,
        'resource_item' => null,
        'resource_type' => null,
        'tags' => null,
        'team_space_id' => 'int64',
        'title' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'aspect_ratio' => 'AspectRatio',
        'description' => 'Description',
        'folder_id' => 'FolderId',
        'media_extension' => 'MediaExtension',
        'not_save_to_asset' => 'NotSaveToAsset',
        'resource_item' => 'ResourceItem',
        'resource_type' => 'ResourceType',
        'tags' => 'Tags',
        'team_space_id' => 'TeamSpaceId',
        'title' => 'Title'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'aspect_ratio' => 'setAspectRatio',
        'description' => 'setDescription',
        'folder_id' => 'setFolderId',
        'media_extension' => 'setMediaExtension',
        'not_save_to_asset' => 'setNotSaveToAsset',
        'resource_item' => 'setResourceItem',
        'resource_type' => 'setResourceType',
        'tags' => 'setTags',
        'team_space_id' => 'setTeamSpaceId',
        'title' => 'setTitle'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'aspect_ratio' => 'getAspectRatio',
        'description' => 'getDescription',
        'folder_id' => 'getFolderId',
        'media_extension' => 'getMediaExtension',
        'not_save_to_asset' => 'getNotSaveToAsset',
        'resource_item' => 'getResourceItem',
        'resource_type' => 'getResourceType',
        'tags' => 'getTags',
        'team_space_id' => 'getTeamSpaceId',
        'title' => 'getTitle'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['aspect_ratio'] = isset($data['aspect_ratio']) ? $data['aspect_ratio'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['folder_id'] = isset($data['folder_id']) ? $data['folder_id'] : null;
        $this->container['media_extension'] = isset($data['media_extension']) ? $data['media_extension'] : null;
        $this->container['not_save_to_asset'] = isset($data['not_save_to_asset']) ? $data['not_save_to_asset'] : null;
        $this->container['resource_item'] = isset($data['resource_item']) ? $data['resource_item'] : null;
        $this->container['resource_type'] = isset($data['resource_type']) ? $data['resource_type'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['team_space_id'] = isset($data['team_space_id']) ? $data['team_space_id'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets aspect_ratio
     *
     * @return string
     */
    public function getAspectRatio()
    {
        return $this->container['aspect_ratio'];
    }

    /**
     * Sets aspect_ratio
     *
     * @param string $aspect_ratio aspect_ratio
     *
     * @return $this
     */
    public function setAspectRatio($aspect_ratio)
    {
        $this->container['aspect_ratio'] = $aspect_ratio;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets folder_id
     *
     * @return int
     */
    public function getFolderId()
    {
        return $this->container['folder_id'];
    }

    /**
     * Sets folder_id
     *
     * @param int $folder_id folder_id
     *
     * @return $this
     */
    public function setFolderId($folder_id)
    {
        $this->container['folder_id'] = $folder_id;

        return $this;
    }

    /**
     * Gets media_extension
     *
     * @return string
     */
    public function getMediaExtension()
    {
        return $this->container['media_extension'];
    }

    /**
     * Sets media_extension
     *
     * @param string $media_extension media_extension
     *
     * @return $this
     */
    public function setMediaExtension($media_extension)
    {
        $this->container['media_extension'] = $media_extension;

        return $this;
    }

    /**
     * Gets not_save_to_asset
     *
     * @return bool
     */
    public function getNotSaveToAsset()
    {
        return $this->container['not_save_to_asset'];
    }

    /**
     * Sets not_save_to_asset
     *
     * @param bool $not_save_to_asset not_save_to_asset
     *
     * @return $this
     */
    public function setNotSaveToAsset($not_save_to_asset)
    {
        $this->container['not_save_to_asset'] = $not_save_to_asset;

        return $this;
    }

    /**
     * Gets resource_item
     *
     * @return string
     */
    public function getResourceItem()
    {
        return $this->container['resource_item'];
    }

    /**
     * Sets resource_item
     *
     * @param string $resource_item resource_item
     *
     * @return $this
     */
    public function setResourceItem($resource_item)
    {
        $this->container['resource_item'] = $resource_item;

        return $this;
    }

    /**
     * Gets resource_type
     *
     * @return string
     */
    public function getResourceType()
    {
        return $this->container['resource_type'];
    }

    /**
     * Sets resource_type
     *
     * @param string $resource_type resource_type
     *
     * @return $this
     */
    public function setResourceType($resource_type)
    {
        $this->container['resource_type'] = $resource_type;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[] $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets team_space_id
     *
     * @return int
     */
    public function getTeamSpaceId()
    {
        return $this->container['team_space_id'];
    }

    /**
     * Sets team_space_id
     *
     * @param int $team_space_id team_space_id
     *
     * @return $this
     */
    public function setTeamSpaceId($team_space_id)
    {
        $this->container['team_space_id'] = $team_space_id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

