<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Kickart\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class GetTenantConfigResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetTenantConfigResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ai_template_banners' => 'string[]',
        'ai_template_doc' => 'string',
        'application_website' => 'string',
        'auth_sub_id' => 'string',
        'auth_sub_name' => 'string',
        'auth_sub_type' => 'int',
        'backend_callback' => 'string',
        'banners' => 'string[]',
        'callback_domain_white_lists' => 'string',
        'chrome_trial' => 'string',
        'cname' => 'string',
        'created_at' => 'int',
        'derived_uid' => 'string',
        'domain_name' => 'string',
        'domain_status' => 'int',
        'editor_icon' => 'string',
        'home_page_configs' => 'string[]',
        'home_page_path' => 'string',
        'is_has_auth' => 'int',
        'logout_redirect_url' => 'string',
        'name' => 'string',
        'nick_name' => 'string',
        'platform_logo' => 'string',
        'public_key' => 'string',
        'resource_op_appid' => 'string',
        'resource_op_appname' => 'string',
        'tenant_id' => 'int',
        'tools' => 'string[]',
        'updated_at' => 'int',
        'user_id' => 'string',
        'web_tag' => 'string',
        'web_tag_logo' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ai_template_banners' => null,
        'ai_template_doc' => null,
        'application_website' => null,
        'auth_sub_id' => null,
        'auth_sub_name' => null,
        'auth_sub_type' => 'int32',
        'backend_callback' => null,
        'banners' => null,
        'callback_domain_white_lists' => null,
        'chrome_trial' => null,
        'cname' => null,
        'created_at' => 'int32',
        'derived_uid' => null,
        'domain_name' => null,
        'domain_status' => 'int32',
        'editor_icon' => null,
        'home_page_configs' => null,
        'home_page_path' => null,
        'is_has_auth' => 'int32',
        'logout_redirect_url' => null,
        'name' => null,
        'nick_name' => null,
        'platform_logo' => null,
        'public_key' => null,
        'resource_op_appid' => null,
        'resource_op_appname' => null,
        'tenant_id' => 'int32',
        'tools' => null,
        'updated_at' => 'int32',
        'user_id' => null,
        'web_tag' => null,
        'web_tag_logo' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ai_template_banners' => 'AiTemplateBanners',
        'ai_template_doc' => 'AiTemplateDoc',
        'application_website' => 'ApplicationWebsite',
        'auth_sub_id' => 'AuthSubId',
        'auth_sub_name' => 'AuthSubName',
        'auth_sub_type' => 'AuthSubType',
        'backend_callback' => 'BackendCallback',
        'banners' => 'Banners',
        'callback_domain_white_lists' => 'CallbackDomainWhiteLists',
        'chrome_trial' => 'ChromeTrial',
        'cname' => 'Cname',
        'created_at' => 'CreatedAt',
        'derived_uid' => 'DerivedUid',
        'domain_name' => 'DomainName',
        'domain_status' => 'DomainStatus',
        'editor_icon' => 'EditorIcon',
        'home_page_configs' => 'HomePageConfigs',
        'home_page_path' => 'HomePagePath',
        'is_has_auth' => 'IsHasAuth',
        'logout_redirect_url' => 'LogoutRedirectUrl',
        'name' => 'Name',
        'nick_name' => 'NickName',
        'platform_logo' => 'PlatformLogo',
        'public_key' => 'PublicKey',
        'resource_op_appid' => 'ResourceOpAppid',
        'resource_op_appname' => 'ResourceOpAppname',
        'tenant_id' => 'TenantId',
        'tools' => 'Tools',
        'updated_at' => 'UpdatedAt',
        'user_id' => 'UserId',
        'web_tag' => 'WebTag',
        'web_tag_logo' => 'WebTagLogo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ai_template_banners' => 'setAiTemplateBanners',
        'ai_template_doc' => 'setAiTemplateDoc',
        'application_website' => 'setApplicationWebsite',
        'auth_sub_id' => 'setAuthSubId',
        'auth_sub_name' => 'setAuthSubName',
        'auth_sub_type' => 'setAuthSubType',
        'backend_callback' => 'setBackendCallback',
        'banners' => 'setBanners',
        'callback_domain_white_lists' => 'setCallbackDomainWhiteLists',
        'chrome_trial' => 'setChromeTrial',
        'cname' => 'setCname',
        'created_at' => 'setCreatedAt',
        'derived_uid' => 'setDerivedUid',
        'domain_name' => 'setDomainName',
        'domain_status' => 'setDomainStatus',
        'editor_icon' => 'setEditorIcon',
        'home_page_configs' => 'setHomePageConfigs',
        'home_page_path' => 'setHomePagePath',
        'is_has_auth' => 'setIsHasAuth',
        'logout_redirect_url' => 'setLogoutRedirectUrl',
        'name' => 'setName',
        'nick_name' => 'setNickName',
        'platform_logo' => 'setPlatformLogo',
        'public_key' => 'setPublicKey',
        'resource_op_appid' => 'setResourceOpAppid',
        'resource_op_appname' => 'setResourceOpAppname',
        'tenant_id' => 'setTenantId',
        'tools' => 'setTools',
        'updated_at' => 'setUpdatedAt',
        'user_id' => 'setUserId',
        'web_tag' => 'setWebTag',
        'web_tag_logo' => 'setWebTagLogo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ai_template_banners' => 'getAiTemplateBanners',
        'ai_template_doc' => 'getAiTemplateDoc',
        'application_website' => 'getApplicationWebsite',
        'auth_sub_id' => 'getAuthSubId',
        'auth_sub_name' => 'getAuthSubName',
        'auth_sub_type' => 'getAuthSubType',
        'backend_callback' => 'getBackendCallback',
        'banners' => 'getBanners',
        'callback_domain_white_lists' => 'getCallbackDomainWhiteLists',
        'chrome_trial' => 'getChromeTrial',
        'cname' => 'getCname',
        'created_at' => 'getCreatedAt',
        'derived_uid' => 'getDerivedUid',
        'domain_name' => 'getDomainName',
        'domain_status' => 'getDomainStatus',
        'editor_icon' => 'getEditorIcon',
        'home_page_configs' => 'getHomePageConfigs',
        'home_page_path' => 'getHomePagePath',
        'is_has_auth' => 'getIsHasAuth',
        'logout_redirect_url' => 'getLogoutRedirectUrl',
        'name' => 'getName',
        'nick_name' => 'getNickName',
        'platform_logo' => 'getPlatformLogo',
        'public_key' => 'getPublicKey',
        'resource_op_appid' => 'getResourceOpAppid',
        'resource_op_appname' => 'getResourceOpAppname',
        'tenant_id' => 'getTenantId',
        'tools' => 'getTools',
        'updated_at' => 'getUpdatedAt',
        'user_id' => 'getUserId',
        'web_tag' => 'getWebTag',
        'web_tag_logo' => 'getWebTagLogo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['ai_template_banners'] = isset($data['ai_template_banners']) ? $data['ai_template_banners'] : null;
        $this->container['ai_template_doc'] = isset($data['ai_template_doc']) ? $data['ai_template_doc'] : null;
        $this->container['application_website'] = isset($data['application_website']) ? $data['application_website'] : null;
        $this->container['auth_sub_id'] = isset($data['auth_sub_id']) ? $data['auth_sub_id'] : null;
        $this->container['auth_sub_name'] = isset($data['auth_sub_name']) ? $data['auth_sub_name'] : null;
        $this->container['auth_sub_type'] = isset($data['auth_sub_type']) ? $data['auth_sub_type'] : null;
        $this->container['backend_callback'] = isset($data['backend_callback']) ? $data['backend_callback'] : null;
        $this->container['banners'] = isset($data['banners']) ? $data['banners'] : null;
        $this->container['callback_domain_white_lists'] = isset($data['callback_domain_white_lists']) ? $data['callback_domain_white_lists'] : null;
        $this->container['chrome_trial'] = isset($data['chrome_trial']) ? $data['chrome_trial'] : null;
        $this->container['cname'] = isset($data['cname']) ? $data['cname'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['derived_uid'] = isset($data['derived_uid']) ? $data['derived_uid'] : null;
        $this->container['domain_name'] = isset($data['domain_name']) ? $data['domain_name'] : null;
        $this->container['domain_status'] = isset($data['domain_status']) ? $data['domain_status'] : null;
        $this->container['editor_icon'] = isset($data['editor_icon']) ? $data['editor_icon'] : null;
        $this->container['home_page_configs'] = isset($data['home_page_configs']) ? $data['home_page_configs'] : null;
        $this->container['home_page_path'] = isset($data['home_page_path']) ? $data['home_page_path'] : null;
        $this->container['is_has_auth'] = isset($data['is_has_auth']) ? $data['is_has_auth'] : null;
        $this->container['logout_redirect_url'] = isset($data['logout_redirect_url']) ? $data['logout_redirect_url'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['nick_name'] = isset($data['nick_name']) ? $data['nick_name'] : null;
        $this->container['platform_logo'] = isset($data['platform_logo']) ? $data['platform_logo'] : null;
        $this->container['public_key'] = isset($data['public_key']) ? $data['public_key'] : null;
        $this->container['resource_op_appid'] = isset($data['resource_op_appid']) ? $data['resource_op_appid'] : null;
        $this->container['resource_op_appname'] = isset($data['resource_op_appname']) ? $data['resource_op_appname'] : null;
        $this->container['tenant_id'] = isset($data['tenant_id']) ? $data['tenant_id'] : null;
        $this->container['tools'] = isset($data['tools']) ? $data['tools'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
        $this->container['user_id'] = isset($data['user_id']) ? $data['user_id'] : null;
        $this->container['web_tag'] = isset($data['web_tag']) ? $data['web_tag'] : null;
        $this->container['web_tag_logo'] = isset($data['web_tag_logo']) ? $data['web_tag_logo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ai_template_banners
     *
     * @return string[]
     */
    public function getAiTemplateBanners()
    {
        return $this->container['ai_template_banners'];
    }

    /**
     * Sets ai_template_banners
     *
     * @param string[] $ai_template_banners ai_template_banners
     *
     * @return $this
     */
    public function setAiTemplateBanners($ai_template_banners)
    {
        $this->container['ai_template_banners'] = $ai_template_banners;

        return $this;
    }

    /**
     * Gets ai_template_doc
     *
     * @return string
     */
    public function getAiTemplateDoc()
    {
        return $this->container['ai_template_doc'];
    }

    /**
     * Sets ai_template_doc
     *
     * @param string $ai_template_doc ai_template_doc
     *
     * @return $this
     */
    public function setAiTemplateDoc($ai_template_doc)
    {
        $this->container['ai_template_doc'] = $ai_template_doc;

        return $this;
    }

    /**
     * Gets application_website
     *
     * @return string
     */
    public function getApplicationWebsite()
    {
        return $this->container['application_website'];
    }

    /**
     * Sets application_website
     *
     * @param string $application_website application_website
     *
     * @return $this
     */
    public function setApplicationWebsite($application_website)
    {
        $this->container['application_website'] = $application_website;

        return $this;
    }

    /**
     * Gets auth_sub_id
     *
     * @return string
     */
    public function getAuthSubId()
    {
        return $this->container['auth_sub_id'];
    }

    /**
     * Sets auth_sub_id
     *
     * @param string $auth_sub_id auth_sub_id
     *
     * @return $this
     */
    public function setAuthSubId($auth_sub_id)
    {
        $this->container['auth_sub_id'] = $auth_sub_id;

        return $this;
    }

    /**
     * Gets auth_sub_name
     *
     * @return string
     */
    public function getAuthSubName()
    {
        return $this->container['auth_sub_name'];
    }

    /**
     * Sets auth_sub_name
     *
     * @param string $auth_sub_name auth_sub_name
     *
     * @return $this
     */
    public function setAuthSubName($auth_sub_name)
    {
        $this->container['auth_sub_name'] = $auth_sub_name;

        return $this;
    }

    /**
     * Gets auth_sub_type
     *
     * @return int
     */
    public function getAuthSubType()
    {
        return $this->container['auth_sub_type'];
    }

    /**
     * Sets auth_sub_type
     *
     * @param int $auth_sub_type auth_sub_type
     *
     * @return $this
     */
    public function setAuthSubType($auth_sub_type)
    {
        $this->container['auth_sub_type'] = $auth_sub_type;

        return $this;
    }

    /**
     * Gets backend_callback
     *
     * @return string
     */
    public function getBackendCallback()
    {
        return $this->container['backend_callback'];
    }

    /**
     * Sets backend_callback
     *
     * @param string $backend_callback backend_callback
     *
     * @return $this
     */
    public function setBackendCallback($backend_callback)
    {
        $this->container['backend_callback'] = $backend_callback;

        return $this;
    }

    /**
     * Gets banners
     *
     * @return string[]
     */
    public function getBanners()
    {
        return $this->container['banners'];
    }

    /**
     * Sets banners
     *
     * @param string[] $banners banners
     *
     * @return $this
     */
    public function setBanners($banners)
    {
        $this->container['banners'] = $banners;

        return $this;
    }

    /**
     * Gets callback_domain_white_lists
     *
     * @return string
     */
    public function getCallbackDomainWhiteLists()
    {
        return $this->container['callback_domain_white_lists'];
    }

    /**
     * Sets callback_domain_white_lists
     *
     * @param string $callback_domain_white_lists callback_domain_white_lists
     *
     * @return $this
     */
    public function setCallbackDomainWhiteLists($callback_domain_white_lists)
    {
        $this->container['callback_domain_white_lists'] = $callback_domain_white_lists;

        return $this;
    }

    /**
     * Gets chrome_trial
     *
     * @return string
     */
    public function getChromeTrial()
    {
        return $this->container['chrome_trial'];
    }

    /**
     * Sets chrome_trial
     *
     * @param string $chrome_trial chrome_trial
     *
     * @return $this
     */
    public function setChromeTrial($chrome_trial)
    {
        $this->container['chrome_trial'] = $chrome_trial;

        return $this;
    }

    /**
     * Gets cname
     *
     * @return string
     */
    public function getCname()
    {
        return $this->container['cname'];
    }

    /**
     * Sets cname
     *
     * @param string $cname cname
     *
     * @return $this
     */
    public function setCname($cname)
    {
        $this->container['cname'] = $cname;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param int $created_at created_at
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets derived_uid
     *
     * @return string
     */
    public function getDerivedUid()
    {
        return $this->container['derived_uid'];
    }

    /**
     * Sets derived_uid
     *
     * @param string $derived_uid derived_uid
     *
     * @return $this
     */
    public function setDerivedUid($derived_uid)
    {
        $this->container['derived_uid'] = $derived_uid;

        return $this;
    }

    /**
     * Gets domain_name
     *
     * @return string
     */
    public function getDomainName()
    {
        return $this->container['domain_name'];
    }

    /**
     * Sets domain_name
     *
     * @param string $domain_name domain_name
     *
     * @return $this
     */
    public function setDomainName($domain_name)
    {
        $this->container['domain_name'] = $domain_name;

        return $this;
    }

    /**
     * Gets domain_status
     *
     * @return int
     */
    public function getDomainStatus()
    {
        return $this->container['domain_status'];
    }

    /**
     * Sets domain_status
     *
     * @param int $domain_status domain_status
     *
     * @return $this
     */
    public function setDomainStatus($domain_status)
    {
        $this->container['domain_status'] = $domain_status;

        return $this;
    }

    /**
     * Gets editor_icon
     *
     * @return string
     */
    public function getEditorIcon()
    {
        return $this->container['editor_icon'];
    }

    /**
     * Sets editor_icon
     *
     * @param string $editor_icon editor_icon
     *
     * @return $this
     */
    public function setEditorIcon($editor_icon)
    {
        $this->container['editor_icon'] = $editor_icon;

        return $this;
    }

    /**
     * Gets home_page_configs
     *
     * @return string[]
     */
    public function getHomePageConfigs()
    {
        return $this->container['home_page_configs'];
    }

    /**
     * Sets home_page_configs
     *
     * @param string[] $home_page_configs home_page_configs
     *
     * @return $this
     */
    public function setHomePageConfigs($home_page_configs)
    {
        $this->container['home_page_configs'] = $home_page_configs;

        return $this;
    }

    /**
     * Gets home_page_path
     *
     * @return string
     */
    public function getHomePagePath()
    {
        return $this->container['home_page_path'];
    }

    /**
     * Sets home_page_path
     *
     * @param string $home_page_path home_page_path
     *
     * @return $this
     */
    public function setHomePagePath($home_page_path)
    {
        $this->container['home_page_path'] = $home_page_path;

        return $this;
    }

    /**
     * Gets is_has_auth
     *
     * @return int
     */
    public function getIsHasAuth()
    {
        return $this->container['is_has_auth'];
    }

    /**
     * Sets is_has_auth
     *
     * @param int $is_has_auth is_has_auth
     *
     * @return $this
     */
    public function setIsHasAuth($is_has_auth)
    {
        $this->container['is_has_auth'] = $is_has_auth;

        return $this;
    }

    /**
     * Gets logout_redirect_url
     *
     * @return string
     */
    public function getLogoutRedirectUrl()
    {
        return $this->container['logout_redirect_url'];
    }

    /**
     * Sets logout_redirect_url
     *
     * @param string $logout_redirect_url logout_redirect_url
     *
     * @return $this
     */
    public function setLogoutRedirectUrl($logout_redirect_url)
    {
        $this->container['logout_redirect_url'] = $logout_redirect_url;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets nick_name
     *
     * @return string
     */
    public function getNickName()
    {
        return $this->container['nick_name'];
    }

    /**
     * Sets nick_name
     *
     * @param string $nick_name nick_name
     *
     * @return $this
     */
    public function setNickName($nick_name)
    {
        $this->container['nick_name'] = $nick_name;

        return $this;
    }

    /**
     * Gets platform_logo
     *
     * @return string
     */
    public function getPlatformLogo()
    {
        return $this->container['platform_logo'];
    }

    /**
     * Sets platform_logo
     *
     * @param string $platform_logo platform_logo
     *
     * @return $this
     */
    public function setPlatformLogo($platform_logo)
    {
        $this->container['platform_logo'] = $platform_logo;

        return $this;
    }

    /**
     * Gets public_key
     *
     * @return string
     */
    public function getPublicKey()
    {
        return $this->container['public_key'];
    }

    /**
     * Sets public_key
     *
     * @param string $public_key public_key
     *
     * @return $this
     */
    public function setPublicKey($public_key)
    {
        $this->container['public_key'] = $public_key;

        return $this;
    }

    /**
     * Gets resource_op_appid
     *
     * @return string
     */
    public function getResourceOpAppid()
    {
        return $this->container['resource_op_appid'];
    }

    /**
     * Sets resource_op_appid
     *
     * @param string $resource_op_appid resource_op_appid
     *
     * @return $this
     */
    public function setResourceOpAppid($resource_op_appid)
    {
        $this->container['resource_op_appid'] = $resource_op_appid;

        return $this;
    }

    /**
     * Gets resource_op_appname
     *
     * @return string
     */
    public function getResourceOpAppname()
    {
        return $this->container['resource_op_appname'];
    }

    /**
     * Sets resource_op_appname
     *
     * @param string $resource_op_appname resource_op_appname
     *
     * @return $this
     */
    public function setResourceOpAppname($resource_op_appname)
    {
        $this->container['resource_op_appname'] = $resource_op_appname;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return int
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int $tenant_id tenant_id
     *
     * @return $this
     */
    public function setTenantId($tenant_id)
    {
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets tools
     *
     * @return string[]
     */
    public function getTools()
    {
        return $this->container['tools'];
    }

    /**
     * Sets tools
     *
     * @param string[] $tools tools
     *
     * @return $this
     */
    public function setTools($tools)
    {
        $this->container['tools'] = $tools;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return int
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param int $updated_at updated_at
     *
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string $user_id user_id
     *
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets web_tag
     *
     * @return string
     */
    public function getWebTag()
    {
        return $this->container['web_tag'];
    }

    /**
     * Sets web_tag
     *
     * @param string $web_tag web_tag
     *
     * @return $this
     */
    public function setWebTag($web_tag)
    {
        $this->container['web_tag'] = $web_tag;

        return $this;
    }

    /**
     * Gets web_tag_logo
     *
     * @return string
     */
    public function getWebTagLogo()
    {
        return $this->container['web_tag_logo'];
    }

    /**
     * Sets web_tag_logo
     *
     * @param string $web_tag_logo web_tag_logo
     *
     * @return $this
     */
    public function setWebTagLogo($web_tag_logo)
    {
        $this->container['web_tag_logo'] = $web_tag_logo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

