<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Kickart\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class ListCreativePointLogsRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ListCreativePointLogsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'consumer_item_ids' => 'int[]',
        'from_ts' => 'int',
        'operator_ids' => 'string[]',
        'page' => 'int',
        'page_size' => 'int',
        'to_ts' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'consumer_item_ids' => 'int32',
        'from_ts' => 'int32',
        'operator_ids' => null,
        'page' => 'int32',
        'page_size' => 'int32',
        'to_ts' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'consumer_item_ids' => 'ConsumerItemIds',
        'from_ts' => 'FromTs',
        'operator_ids' => 'OperatorIds',
        'page' => 'Page',
        'page_size' => 'PageSize',
        'to_ts' => 'ToTs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'consumer_item_ids' => 'setConsumerItemIds',
        'from_ts' => 'setFromTs',
        'operator_ids' => 'setOperatorIds',
        'page' => 'setPage',
        'page_size' => 'setPageSize',
        'to_ts' => 'setToTs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'consumer_item_ids' => 'getConsumerItemIds',
        'from_ts' => 'getFromTs',
        'operator_ids' => 'getOperatorIds',
        'page' => 'getPage',
        'page_size' => 'getPageSize',
        'to_ts' => 'getToTs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['consumer_item_ids'] = isset($data['consumer_item_ids']) ? $data['consumer_item_ids'] : null;
        $this->container['from_ts'] = isset($data['from_ts']) ? $data['from_ts'] : null;
        $this->container['operator_ids'] = isset($data['operator_ids']) ? $data['operator_ids'] : null;
        $this->container['page'] = isset($data['page']) ? $data['page'] : null;
        $this->container['page_size'] = isset($data['page_size']) ? $data['page_size'] : null;
        $this->container['to_ts'] = isset($data['to_ts']) ? $data['to_ts'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets consumer_item_ids
     *
     * @return int[]
     */
    public function getConsumerItemIds()
    {
        return $this->container['consumer_item_ids'];
    }

    /**
     * Sets consumer_item_ids
     *
     * @param int[] $consumer_item_ids consumer_item_ids
     *
     * @return $this
     */
    public function setConsumerItemIds($consumer_item_ids)
    {
        $this->container['consumer_item_ids'] = $consumer_item_ids;

        return $this;
    }

    /**
     * Gets from_ts
     *
     * @return int
     */
    public function getFromTs()
    {
        return $this->container['from_ts'];
    }

    /**
     * Sets from_ts
     *
     * @param int $from_ts from_ts
     *
     * @return $this
     */
    public function setFromTs($from_ts)
    {
        $this->container['from_ts'] = $from_ts;

        return $this;
    }

    /**
     * Gets operator_ids
     *
     * @return string[]
     */
    public function getOperatorIds()
    {
        return $this->container['operator_ids'];
    }

    /**
     * Sets operator_ids
     *
     * @param string[] $operator_ids operator_ids
     *
     * @return $this
     */
    public function setOperatorIds($operator_ids)
    {
        $this->container['operator_ids'] = $operator_ids;

        return $this;
    }

    /**
     * Gets page
     *
     * @return int
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param int $page page
     *
     * @return $this
     */
    public function setPage($page)
    {
        $this->container['page'] = $page;

        return $this;
    }

    /**
     * Gets page_size
     *
     * @return int
     */
    public function getPageSize()
    {
        return $this->container['page_size'];
    }

    /**
     * Sets page_size
     *
     * @param int $page_size page_size
     *
     * @return $this
     */
    public function setPageSize($page_size)
    {
        $this->container['page_size'] = $page_size;

        return $this;
    }

    /**
     * Gets to_ts
     *
     * @return int
     */
    public function getToTs()
    {
        return $this->container['to_ts'];
    }

    /**
     * Sets to_ts
     *
     * @param int $to_ts to_ts
     *
     * @return $this
     */
    public function setToTs($to_ts)
    {
        $this->container['to_ts'] = $to_ts;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

