<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Alb\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class CreateLoadBalancerRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateLoadBalancerRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'address_ip_version' => 'string',
        'bandwidth_package_id' => 'string',
        'client_token' => 'string',
        'delete_protection' => 'string',
        'description' => 'string',
        'eip_billing_config' => '\Byteplus\Alb\Model\EipBillingConfigForCreateLoadBalancerInput',
        'ipv6_eip_billing_config' => '\Byteplus\Alb\Model\Ipv6EipBillingConfigForCreateLoadBalancerInput',
        'load_balancer_billing_type' => 'int',
        'load_balancer_edition' => 'string',
        'load_balancer_name' => 'string',
        'modification_protection_reason' => 'string',
        'modification_protection_status' => 'string',
        'project_name' => 'string',
        'region_id' => 'string',
        'subnet_id' => 'string',
        'tags' => '\Byteplus\Alb\Model\TagForCreateLoadBalancerInput[]',
        'type' => 'string',
        'vpc_id' => 'string',
        'zone_mappings' => '\Byteplus\Alb\Model\ZoneMappingForCreateLoadBalancerInput[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'address_ip_version' => null,
        'bandwidth_package_id' => null,
        'client_token' => null,
        'delete_protection' => null,
        'description' => null,
        'eip_billing_config' => null,
        'ipv6_eip_billing_config' => null,
        'load_balancer_billing_type' => null,
        'load_balancer_edition' => null,
        'load_balancer_name' => null,
        'modification_protection_reason' => null,
        'modification_protection_status' => null,
        'project_name' => null,
        'region_id' => null,
        'subnet_id' => null,
        'tags' => null,
        'type' => null,
        'vpc_id' => null,
        'zone_mappings' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address_ip_version' => 'AddressIpVersion',
        'bandwidth_package_id' => 'BandwidthPackageId',
        'client_token' => 'ClientToken',
        'delete_protection' => 'DeleteProtection',
        'description' => 'Description',
        'eip_billing_config' => 'EipBillingConfig',
        'ipv6_eip_billing_config' => 'Ipv6EipBillingConfig',
        'load_balancer_billing_type' => 'LoadBalancerBillingType',
        'load_balancer_edition' => 'LoadBalancerEdition',
        'load_balancer_name' => 'LoadBalancerName',
        'modification_protection_reason' => 'ModificationProtectionReason',
        'modification_protection_status' => 'ModificationProtectionStatus',
        'project_name' => 'ProjectName',
        'region_id' => 'RegionId',
        'subnet_id' => 'SubnetId',
        'tags' => 'Tags',
        'type' => 'Type',
        'vpc_id' => 'VpcId',
        'zone_mappings' => 'ZoneMappings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address_ip_version' => 'setAddressIpVersion',
        'bandwidth_package_id' => 'setBandwidthPackageId',
        'client_token' => 'setClientToken',
        'delete_protection' => 'setDeleteProtection',
        'description' => 'setDescription',
        'eip_billing_config' => 'setEipBillingConfig',
        'ipv6_eip_billing_config' => 'setIpv6EipBillingConfig',
        'load_balancer_billing_type' => 'setLoadBalancerBillingType',
        'load_balancer_edition' => 'setLoadBalancerEdition',
        'load_balancer_name' => 'setLoadBalancerName',
        'modification_protection_reason' => 'setModificationProtectionReason',
        'modification_protection_status' => 'setModificationProtectionStatus',
        'project_name' => 'setProjectName',
        'region_id' => 'setRegionId',
        'subnet_id' => 'setSubnetId',
        'tags' => 'setTags',
        'type' => 'setType',
        'vpc_id' => 'setVpcId',
        'zone_mappings' => 'setZoneMappings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address_ip_version' => 'getAddressIpVersion',
        'bandwidth_package_id' => 'getBandwidthPackageId',
        'client_token' => 'getClientToken',
        'delete_protection' => 'getDeleteProtection',
        'description' => 'getDescription',
        'eip_billing_config' => 'getEipBillingConfig',
        'ipv6_eip_billing_config' => 'getIpv6EipBillingConfig',
        'load_balancer_billing_type' => 'getLoadBalancerBillingType',
        'load_balancer_edition' => 'getLoadBalancerEdition',
        'load_balancer_name' => 'getLoadBalancerName',
        'modification_protection_reason' => 'getModificationProtectionReason',
        'modification_protection_status' => 'getModificationProtectionStatus',
        'project_name' => 'getProjectName',
        'region_id' => 'getRegionId',
        'subnet_id' => 'getSubnetId',
        'tags' => 'getTags',
        'type' => 'getType',
        'vpc_id' => 'getVpcId',
        'zone_mappings' => 'getZoneMappings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['address_ip_version'] = isset($data['address_ip_version']) ? $data['address_ip_version'] : null;
        $this->container['bandwidth_package_id'] = isset($data['bandwidth_package_id']) ? $data['bandwidth_package_id'] : null;
        $this->container['client_token'] = isset($data['client_token']) ? $data['client_token'] : null;
        $this->container['delete_protection'] = isset($data['delete_protection']) ? $data['delete_protection'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['eip_billing_config'] = isset($data['eip_billing_config']) ? $data['eip_billing_config'] : null;
        $this->container['ipv6_eip_billing_config'] = isset($data['ipv6_eip_billing_config']) ? $data['ipv6_eip_billing_config'] : null;
        $this->container['load_balancer_billing_type'] = isset($data['load_balancer_billing_type']) ? $data['load_balancer_billing_type'] : null;
        $this->container['load_balancer_edition'] = isset($data['load_balancer_edition']) ? $data['load_balancer_edition'] : null;
        $this->container['load_balancer_name'] = isset($data['load_balancer_name']) ? $data['load_balancer_name'] : null;
        $this->container['modification_protection_reason'] = isset($data['modification_protection_reason']) ? $data['modification_protection_reason'] : null;
        $this->container['modification_protection_status'] = isset($data['modification_protection_status']) ? $data['modification_protection_status'] : null;
        $this->container['project_name'] = isset($data['project_name']) ? $data['project_name'] : null;
        $this->container['region_id'] = isset($data['region_id']) ? $data['region_id'] : null;
        $this->container['subnet_id'] = isset($data['subnet_id']) ? $data['subnet_id'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['vpc_id'] = isset($data['vpc_id']) ? $data['vpc_id'] : null;
        $this->container['zone_mappings'] = isset($data['zone_mappings']) ? $data['zone_mappings'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['region_id'] === null) {
            $invalidProperties[] = "'region_id' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address_ip_version
     *
     * @return string
     */
    public function getAddressIpVersion()
    {
        return $this->container['address_ip_version'];
    }

    /**
     * Sets address_ip_version
     *
     * @param string $address_ip_version address_ip_version
     *
     * @return $this
     */
    public function setAddressIpVersion($address_ip_version)
    {
        $this->container['address_ip_version'] = $address_ip_version;

        return $this;
    }

    /**
     * Gets bandwidth_package_id
     *
     * @return string
     */
    public function getBandwidthPackageId()
    {
        return $this->container['bandwidth_package_id'];
    }

    /**
     * Sets bandwidth_package_id
     *
     * @param string $bandwidth_package_id bandwidth_package_id
     *
     * @return $this
     */
    public function setBandwidthPackageId($bandwidth_package_id)
    {
        $this->container['bandwidth_package_id'] = $bandwidth_package_id;

        return $this;
    }

    /**
     * Gets client_token
     *
     * @return string
     */
    public function getClientToken()
    {
        return $this->container['client_token'];
    }

    /**
     * Sets client_token
     *
     * @param string $client_token client_token
     *
     * @return $this
     */
    public function setClientToken($client_token)
    {
        $this->container['client_token'] = $client_token;

        return $this;
    }

    /**
     * Gets delete_protection
     *
     * @return string
     */
    public function getDeleteProtection()
    {
        return $this->container['delete_protection'];
    }

    /**
     * Sets delete_protection
     *
     * @param string $delete_protection delete_protection
     *
     * @return $this
     */
    public function setDeleteProtection($delete_protection)
    {
        $this->container['delete_protection'] = $delete_protection;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets eip_billing_config
     *
     * @return \Byteplus\Alb\Model\EipBillingConfigForCreateLoadBalancerInput
     */
    public function getEipBillingConfig()
    {
        return $this->container['eip_billing_config'];
    }

    /**
     * Sets eip_billing_config
     *
     * @param \Byteplus\Alb\Model\EipBillingConfigForCreateLoadBalancerInput $eip_billing_config eip_billing_config
     *
     * @return $this
     */
    public function setEipBillingConfig($eip_billing_config)
    {
        $this->container['eip_billing_config'] = $eip_billing_config;

        return $this;
    }

    /**
     * Gets ipv6_eip_billing_config
     *
     * @return \Byteplus\Alb\Model\Ipv6EipBillingConfigForCreateLoadBalancerInput
     */
    public function getIpv6EipBillingConfig()
    {
        return $this->container['ipv6_eip_billing_config'];
    }

    /**
     * Sets ipv6_eip_billing_config
     *
     * @param \Byteplus\Alb\Model\Ipv6EipBillingConfigForCreateLoadBalancerInput $ipv6_eip_billing_config ipv6_eip_billing_config
     *
     * @return $this
     */
    public function setIpv6EipBillingConfig($ipv6_eip_billing_config)
    {
        $this->container['ipv6_eip_billing_config'] = $ipv6_eip_billing_config;

        return $this;
    }

    /**
     * Gets load_balancer_billing_type
     *
     * @return int
     */
    public function getLoadBalancerBillingType()
    {
        return $this->container['load_balancer_billing_type'];
    }

    /**
     * Sets load_balancer_billing_type
     *
     * @param int $load_balancer_billing_type load_balancer_billing_type
     *
     * @return $this
     */
    public function setLoadBalancerBillingType($load_balancer_billing_type)
    {
        $this->container['load_balancer_billing_type'] = $load_balancer_billing_type;

        return $this;
    }

    /**
     * Gets load_balancer_edition
     *
     * @return string
     */
    public function getLoadBalancerEdition()
    {
        return $this->container['load_balancer_edition'];
    }

    /**
     * Sets load_balancer_edition
     *
     * @param string $load_balancer_edition load_balancer_edition
     *
     * @return $this
     */
    public function setLoadBalancerEdition($load_balancer_edition)
    {
        $this->container['load_balancer_edition'] = $load_balancer_edition;

        return $this;
    }

    /**
     * Gets load_balancer_name
     *
     * @return string
     */
    public function getLoadBalancerName()
    {
        return $this->container['load_balancer_name'];
    }

    /**
     * Sets load_balancer_name
     *
     * @param string $load_balancer_name load_balancer_name
     *
     * @return $this
     */
    public function setLoadBalancerName($load_balancer_name)
    {
        $this->container['load_balancer_name'] = $load_balancer_name;

        return $this;
    }

    /**
     * Gets modification_protection_reason
     *
     * @return string
     */
    public function getModificationProtectionReason()
    {
        return $this->container['modification_protection_reason'];
    }

    /**
     * Sets modification_protection_reason
     *
     * @param string $modification_protection_reason modification_protection_reason
     *
     * @return $this
     */
    public function setModificationProtectionReason($modification_protection_reason)
    {
        $this->container['modification_protection_reason'] = $modification_protection_reason;

        return $this;
    }

    /**
     * Gets modification_protection_status
     *
     * @return string
     */
    public function getModificationProtectionStatus()
    {
        return $this->container['modification_protection_status'];
    }

    /**
     * Sets modification_protection_status
     *
     * @param string $modification_protection_status modification_protection_status
     *
     * @return $this
     */
    public function setModificationProtectionStatus($modification_protection_status)
    {
        $this->container['modification_protection_status'] = $modification_protection_status;

        return $this;
    }

    /**
     * Gets project_name
     *
     * @return string
     */
    public function getProjectName()
    {
        return $this->container['project_name'];
    }

    /**
     * Sets project_name
     *
     * @param string $project_name project_name
     *
     * @return $this
     */
    public function setProjectName($project_name)
    {
        $this->container['project_name'] = $project_name;

        return $this;
    }

    /**
     * Gets region_id
     *
     * @return string
     */
    public function getRegionId()
    {
        return $this->container['region_id'];
    }

    /**
     * Sets region_id
     *
     * @param string $region_id region_id
     *
     * @return $this
     */
    public function setRegionId($region_id)
    {
        $this->container['region_id'] = $region_id;

        return $this;
    }

    /**
     * Gets subnet_id
     *
     * @return string
     */
    public function getSubnetId()
    {
        return $this->container['subnet_id'];
    }

    /**
     * Sets subnet_id
     *
     * @param string $subnet_id subnet_id
     *
     * @return $this
     */
    public function setSubnetId($subnet_id)
    {
        $this->container['subnet_id'] = $subnet_id;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \Byteplus\Alb\Model\TagForCreateLoadBalancerInput[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \Byteplus\Alb\Model\TagForCreateLoadBalancerInput[] $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets vpc_id
     *
     * @return string
     */
    public function getVpcId()
    {
        return $this->container['vpc_id'];
    }

    /**
     * Sets vpc_id
     *
     * @param string $vpc_id vpc_id
     *
     * @return $this
     */
    public function setVpcId($vpc_id)
    {
        $this->container['vpc_id'] = $vpc_id;

        return $this;
    }

    /**
     * Gets zone_mappings
     *
     * @return \Byteplus\Alb\Model\ZoneMappingForCreateLoadBalancerInput[]
     */
    public function getZoneMappings()
    {
        return $this->container['zone_mappings'];
    }

    /**
     * Sets zone_mappings
     *
     * @param \Byteplus\Alb\Model\ZoneMappingForCreateLoadBalancerInput[] $zone_mappings zone_mappings
     *
     * @return $this
     */
    public function setZoneMappings($zone_mappings)
    {
        $this->container['zone_mappings'] = $zone_mappings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

