<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Alb\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class DescribeLoadBalancerAttributesResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DescribeLoadBalancerAttributesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'access_log' => '\Byteplus\Alb\Model\AccessLogForDescribeLoadBalancerAttributesOutput',
        'address_ip_version' => 'string',
        'business_status' => 'string',
        'create_time' => 'string',
        'dns_name' => 'string',
        'delete_protection' => 'string',
        'deleted_time' => 'string',
        'description' => 'string',
        'eip' => '\Byteplus\Alb\Model\EipForDescribeLoadBalancerAttributesOutput',
        'eip_address' => 'string',
        'eip_id' => 'string',
        'enabled' => 'bool',
        'eni_address' => 'string',
        'eni_id' => 'string',
        'global_accelerators' => '\Byteplus\Alb\Model\GlobalAcceleratorsForDescribeLoadBalancerAttributesOutput',
        'health_log' => '\Byteplus\Alb\Model\HealthLogForDescribeLoadBalancerAttributesOutput',
        'listeners' => '\Byteplus\Alb\Model\ListenerForDescribeLoadBalancerAttributesOutput[]',
        'load_balancer_billing_type' => 'int',
        'load_balancer_edition' => 'string',
        'load_balancer_id' => 'string',
        'load_balancer_name' => 'string',
        'local_addresses' => 'string[]',
        'lock_reason' => 'string',
        'modification_protection_reason' => 'string',
        'modification_protection_status' => 'string',
        'overdue_time' => 'string',
        'project_name' => 'string',
        'request_id' => 'string',
        'sni_auto_match' => 'string',
        'status' => 'string',
        'subnet_id' => 'string',
        'tls_access_log' => '\Byteplus\Alb\Model\TLSAccessLogForDescribeLoadBalancerAttributesOutput',
        'tags' => '\Byteplus\Alb\Model\TagForDescribeLoadBalancerAttributesOutput[]',
        'type' => 'string',
        'update_time' => 'string',
        'vpc_id' => 'string',
        'waf_instance_id' => 'string',
        'waf_protection_enabled' => 'string',
        'zone_mappings' => '\Byteplus\Alb\Model\ZoneMappingForDescribeLoadBalancerAttributesOutput[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'access_log' => null,
        'address_ip_version' => null,
        'business_status' => null,
        'create_time' => null,
        'dns_name' => null,
        'delete_protection' => null,
        'deleted_time' => null,
        'description' => null,
        'eip' => null,
        'eip_address' => null,
        'eip_id' => null,
        'enabled' => null,
        'eni_address' => null,
        'eni_id' => null,
        'global_accelerators' => null,
        'health_log' => null,
        'listeners' => null,
        'load_balancer_billing_type' => null,
        'load_balancer_edition' => null,
        'load_balancer_id' => null,
        'load_balancer_name' => null,
        'local_addresses' => null,
        'lock_reason' => null,
        'modification_protection_reason' => null,
        'modification_protection_status' => null,
        'overdue_time' => null,
        'project_name' => null,
        'request_id' => null,
        'sni_auto_match' => null,
        'status' => null,
        'subnet_id' => null,
        'tls_access_log' => null,
        'tags' => null,
        'type' => null,
        'update_time' => null,
        'vpc_id' => null,
        'waf_instance_id' => null,
        'waf_protection_enabled' => null,
        'zone_mappings' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access_log' => 'AccessLog',
        'address_ip_version' => 'AddressIpVersion',
        'business_status' => 'BusinessStatus',
        'create_time' => 'CreateTime',
        'dns_name' => 'DNSName',
        'delete_protection' => 'DeleteProtection',
        'deleted_time' => 'DeletedTime',
        'description' => 'Description',
        'eip' => 'Eip',
        'eip_address' => 'EipAddress',
        'eip_id' => 'EipId',
        'enabled' => 'Enabled',
        'eni_address' => 'EniAddress',
        'eni_id' => 'EniId',
        'global_accelerators' => 'GlobalAccelerators',
        'health_log' => 'HealthLog',
        'listeners' => 'Listeners',
        'load_balancer_billing_type' => 'LoadBalancerBillingType',
        'load_balancer_edition' => 'LoadBalancerEdition',
        'load_balancer_id' => 'LoadBalancerId',
        'load_balancer_name' => 'LoadBalancerName',
        'local_addresses' => 'LocalAddresses',
        'lock_reason' => 'LockReason',
        'modification_protection_reason' => 'ModificationProtectionReason',
        'modification_protection_status' => 'ModificationProtectionStatus',
        'overdue_time' => 'OverdueTime',
        'project_name' => 'ProjectName',
        'request_id' => 'RequestId',
        'sni_auto_match' => 'SniAutoMatch',
        'status' => 'Status',
        'subnet_id' => 'SubnetId',
        'tls_access_log' => 'TLSAccessLog',
        'tags' => 'Tags',
        'type' => 'Type',
        'update_time' => 'UpdateTime',
        'vpc_id' => 'VpcId',
        'waf_instance_id' => 'WafInstanceId',
        'waf_protection_enabled' => 'WafProtectionEnabled',
        'zone_mappings' => 'ZoneMappings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access_log' => 'setAccessLog',
        'address_ip_version' => 'setAddressIpVersion',
        'business_status' => 'setBusinessStatus',
        'create_time' => 'setCreateTime',
        'dns_name' => 'setDnsName',
        'delete_protection' => 'setDeleteProtection',
        'deleted_time' => 'setDeletedTime',
        'description' => 'setDescription',
        'eip' => 'setEip',
        'eip_address' => 'setEipAddress',
        'eip_id' => 'setEipId',
        'enabled' => 'setEnabled',
        'eni_address' => 'setEniAddress',
        'eni_id' => 'setEniId',
        'global_accelerators' => 'setGlobalAccelerators',
        'health_log' => 'setHealthLog',
        'listeners' => 'setListeners',
        'load_balancer_billing_type' => 'setLoadBalancerBillingType',
        'load_balancer_edition' => 'setLoadBalancerEdition',
        'load_balancer_id' => 'setLoadBalancerId',
        'load_balancer_name' => 'setLoadBalancerName',
        'local_addresses' => 'setLocalAddresses',
        'lock_reason' => 'setLockReason',
        'modification_protection_reason' => 'setModificationProtectionReason',
        'modification_protection_status' => 'setModificationProtectionStatus',
        'overdue_time' => 'setOverdueTime',
        'project_name' => 'setProjectName',
        'request_id' => 'setRequestId',
        'sni_auto_match' => 'setSniAutoMatch',
        'status' => 'setStatus',
        'subnet_id' => 'setSubnetId',
        'tls_access_log' => 'setTlsAccessLog',
        'tags' => 'setTags',
        'type' => 'setType',
        'update_time' => 'setUpdateTime',
        'vpc_id' => 'setVpcId',
        'waf_instance_id' => 'setWafInstanceId',
        'waf_protection_enabled' => 'setWafProtectionEnabled',
        'zone_mappings' => 'setZoneMappings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access_log' => 'getAccessLog',
        'address_ip_version' => 'getAddressIpVersion',
        'business_status' => 'getBusinessStatus',
        'create_time' => 'getCreateTime',
        'dns_name' => 'getDnsName',
        'delete_protection' => 'getDeleteProtection',
        'deleted_time' => 'getDeletedTime',
        'description' => 'getDescription',
        'eip' => 'getEip',
        'eip_address' => 'getEipAddress',
        'eip_id' => 'getEipId',
        'enabled' => 'getEnabled',
        'eni_address' => 'getEniAddress',
        'eni_id' => 'getEniId',
        'global_accelerators' => 'getGlobalAccelerators',
        'health_log' => 'getHealthLog',
        'listeners' => 'getListeners',
        'load_balancer_billing_type' => 'getLoadBalancerBillingType',
        'load_balancer_edition' => 'getLoadBalancerEdition',
        'load_balancer_id' => 'getLoadBalancerId',
        'load_balancer_name' => 'getLoadBalancerName',
        'local_addresses' => 'getLocalAddresses',
        'lock_reason' => 'getLockReason',
        'modification_protection_reason' => 'getModificationProtectionReason',
        'modification_protection_status' => 'getModificationProtectionStatus',
        'overdue_time' => 'getOverdueTime',
        'project_name' => 'getProjectName',
        'request_id' => 'getRequestId',
        'sni_auto_match' => 'getSniAutoMatch',
        'status' => 'getStatus',
        'subnet_id' => 'getSubnetId',
        'tls_access_log' => 'getTlsAccessLog',
        'tags' => 'getTags',
        'type' => 'getType',
        'update_time' => 'getUpdateTime',
        'vpc_id' => 'getVpcId',
        'waf_instance_id' => 'getWafInstanceId',
        'waf_protection_enabled' => 'getWafProtectionEnabled',
        'zone_mappings' => 'getZoneMappings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['access_log'] = isset($data['access_log']) ? $data['access_log'] : null;
        $this->container['address_ip_version'] = isset($data['address_ip_version']) ? $data['address_ip_version'] : null;
        $this->container['business_status'] = isset($data['business_status']) ? $data['business_status'] : null;
        $this->container['create_time'] = isset($data['create_time']) ? $data['create_time'] : null;
        $this->container['dns_name'] = isset($data['dns_name']) ? $data['dns_name'] : null;
        $this->container['delete_protection'] = isset($data['delete_protection']) ? $data['delete_protection'] : null;
        $this->container['deleted_time'] = isset($data['deleted_time']) ? $data['deleted_time'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['eip'] = isset($data['eip']) ? $data['eip'] : null;
        $this->container['eip_address'] = isset($data['eip_address']) ? $data['eip_address'] : null;
        $this->container['eip_id'] = isset($data['eip_id']) ? $data['eip_id'] : null;
        $this->container['enabled'] = isset($data['enabled']) ? $data['enabled'] : null;
        $this->container['eni_address'] = isset($data['eni_address']) ? $data['eni_address'] : null;
        $this->container['eni_id'] = isset($data['eni_id']) ? $data['eni_id'] : null;
        $this->container['global_accelerators'] = isset($data['global_accelerators']) ? $data['global_accelerators'] : null;
        $this->container['health_log'] = isset($data['health_log']) ? $data['health_log'] : null;
        $this->container['listeners'] = isset($data['listeners']) ? $data['listeners'] : null;
        $this->container['load_balancer_billing_type'] = isset($data['load_balancer_billing_type']) ? $data['load_balancer_billing_type'] : null;
        $this->container['load_balancer_edition'] = isset($data['load_balancer_edition']) ? $data['load_balancer_edition'] : null;
        $this->container['load_balancer_id'] = isset($data['load_balancer_id']) ? $data['load_balancer_id'] : null;
        $this->container['load_balancer_name'] = isset($data['load_balancer_name']) ? $data['load_balancer_name'] : null;
        $this->container['local_addresses'] = isset($data['local_addresses']) ? $data['local_addresses'] : null;
        $this->container['lock_reason'] = isset($data['lock_reason']) ? $data['lock_reason'] : null;
        $this->container['modification_protection_reason'] = isset($data['modification_protection_reason']) ? $data['modification_protection_reason'] : null;
        $this->container['modification_protection_status'] = isset($data['modification_protection_status']) ? $data['modification_protection_status'] : null;
        $this->container['overdue_time'] = isset($data['overdue_time']) ? $data['overdue_time'] : null;
        $this->container['project_name'] = isset($data['project_name']) ? $data['project_name'] : null;
        $this->container['request_id'] = isset($data['request_id']) ? $data['request_id'] : null;
        $this->container['sni_auto_match'] = isset($data['sni_auto_match']) ? $data['sni_auto_match'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['subnet_id'] = isset($data['subnet_id']) ? $data['subnet_id'] : null;
        $this->container['tls_access_log'] = isset($data['tls_access_log']) ? $data['tls_access_log'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['update_time'] = isset($data['update_time']) ? $data['update_time'] : null;
        $this->container['vpc_id'] = isset($data['vpc_id']) ? $data['vpc_id'] : null;
        $this->container['waf_instance_id'] = isset($data['waf_instance_id']) ? $data['waf_instance_id'] : null;
        $this->container['waf_protection_enabled'] = isset($data['waf_protection_enabled']) ? $data['waf_protection_enabled'] : null;
        $this->container['zone_mappings'] = isset($data['zone_mappings']) ? $data['zone_mappings'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access_log
     *
     * @return \Byteplus\Alb\Model\AccessLogForDescribeLoadBalancerAttributesOutput
     */
    public function getAccessLog()
    {
        return $this->container['access_log'];
    }

    /**
     * Sets access_log
     *
     * @param \Byteplus\Alb\Model\AccessLogForDescribeLoadBalancerAttributesOutput $access_log access_log
     *
     * @return $this
     */
    public function setAccessLog($access_log)
    {
        $this->container['access_log'] = $access_log;

        return $this;
    }

    /**
     * Gets address_ip_version
     *
     * @return string
     */
    public function getAddressIpVersion()
    {
        return $this->container['address_ip_version'];
    }

    /**
     * Sets address_ip_version
     *
     * @param string $address_ip_version address_ip_version
     *
     * @return $this
     */
    public function setAddressIpVersion($address_ip_version)
    {
        $this->container['address_ip_version'] = $address_ip_version;

        return $this;
    }

    /**
     * Gets business_status
     *
     * @return string
     */
    public function getBusinessStatus()
    {
        return $this->container['business_status'];
    }

    /**
     * Sets business_status
     *
     * @param string $business_status business_status
     *
     * @return $this
     */
    public function setBusinessStatus($business_status)
    {
        $this->container['business_status'] = $business_status;

        return $this;
    }

    /**
     * Gets create_time
     *
     * @return string
     */
    public function getCreateTime()
    {
        return $this->container['create_time'];
    }

    /**
     * Sets create_time
     *
     * @param string $create_time create_time
     *
     * @return $this
     */
    public function setCreateTime($create_time)
    {
        $this->container['create_time'] = $create_time;

        return $this;
    }

    /**
     * Gets dns_name
     *
     * @return string
     */
    public function getDnsName()
    {
        return $this->container['dns_name'];
    }

    /**
     * Sets dns_name
     *
     * @param string $dns_name dns_name
     *
     * @return $this
     */
    public function setDnsName($dns_name)
    {
        $this->container['dns_name'] = $dns_name;

        return $this;
    }

    /**
     * Gets delete_protection
     *
     * @return string
     */
    public function getDeleteProtection()
    {
        return $this->container['delete_protection'];
    }

    /**
     * Sets delete_protection
     *
     * @param string $delete_protection delete_protection
     *
     * @return $this
     */
    public function setDeleteProtection($delete_protection)
    {
        $this->container['delete_protection'] = $delete_protection;

        return $this;
    }

    /**
     * Gets deleted_time
     *
     * @return string
     */
    public function getDeletedTime()
    {
        return $this->container['deleted_time'];
    }

    /**
     * Sets deleted_time
     *
     * @param string $deleted_time deleted_time
     *
     * @return $this
     */
    public function setDeletedTime($deleted_time)
    {
        $this->container['deleted_time'] = $deleted_time;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets eip
     *
     * @return \Byteplus\Alb\Model\EipForDescribeLoadBalancerAttributesOutput
     */
    public function getEip()
    {
        return $this->container['eip'];
    }

    /**
     * Sets eip
     *
     * @param \Byteplus\Alb\Model\EipForDescribeLoadBalancerAttributesOutput $eip eip
     *
     * @return $this
     */
    public function setEip($eip)
    {
        $this->container['eip'] = $eip;

        return $this;
    }

    /**
     * Gets eip_address
     *
     * @return string
     */
    public function getEipAddress()
    {
        return $this->container['eip_address'];
    }

    /**
     * Sets eip_address
     *
     * @param string $eip_address eip_address
     *
     * @return $this
     */
    public function setEipAddress($eip_address)
    {
        $this->container['eip_address'] = $eip_address;

        return $this;
    }

    /**
     * Gets eip_id
     *
     * @return string
     */
    public function getEipId()
    {
        return $this->container['eip_id'];
    }

    /**
     * Sets eip_id
     *
     * @param string $eip_id eip_id
     *
     * @return $this
     */
    public function setEipId($eip_id)
    {
        $this->container['eip_id'] = $eip_id;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool $enabled enabled
     *
     * @return $this
     */
    public function setEnabled($enabled)
    {
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets eni_address
     *
     * @return string
     */
    public function getEniAddress()
    {
        return $this->container['eni_address'];
    }

    /**
     * Sets eni_address
     *
     * @param string $eni_address eni_address
     *
     * @return $this
     */
    public function setEniAddress($eni_address)
    {
        $this->container['eni_address'] = $eni_address;

        return $this;
    }

    /**
     * Gets eni_id
     *
     * @return string
     */
    public function getEniId()
    {
        return $this->container['eni_id'];
    }

    /**
     * Sets eni_id
     *
     * @param string $eni_id eni_id
     *
     * @return $this
     */
    public function setEniId($eni_id)
    {
        $this->container['eni_id'] = $eni_id;

        return $this;
    }

    /**
     * Gets global_accelerators
     *
     * @return \Byteplus\Alb\Model\GlobalAcceleratorsForDescribeLoadBalancerAttributesOutput
     */
    public function getGlobalAccelerators()
    {
        return $this->container['global_accelerators'];
    }

    /**
     * Sets global_accelerators
     *
     * @param \Byteplus\Alb\Model\GlobalAcceleratorsForDescribeLoadBalancerAttributesOutput $global_accelerators global_accelerators
     *
     * @return $this
     */
    public function setGlobalAccelerators($global_accelerators)
    {
        $this->container['global_accelerators'] = $global_accelerators;

        return $this;
    }

    /**
     * Gets health_log
     *
     * @return \Byteplus\Alb\Model\HealthLogForDescribeLoadBalancerAttributesOutput
     */
    public function getHealthLog()
    {
        return $this->container['health_log'];
    }

    /**
     * Sets health_log
     *
     * @param \Byteplus\Alb\Model\HealthLogForDescribeLoadBalancerAttributesOutput $health_log health_log
     *
     * @return $this
     */
    public function setHealthLog($health_log)
    {
        $this->container['health_log'] = $health_log;

        return $this;
    }

    /**
     * Gets listeners
     *
     * @return \Byteplus\Alb\Model\ListenerForDescribeLoadBalancerAttributesOutput[]
     */
    public function getListeners()
    {
        return $this->container['listeners'];
    }

    /**
     * Sets listeners
     *
     * @param \Byteplus\Alb\Model\ListenerForDescribeLoadBalancerAttributesOutput[] $listeners listeners
     *
     * @return $this
     */
    public function setListeners($listeners)
    {
        $this->container['listeners'] = $listeners;

        return $this;
    }

    /**
     * Gets load_balancer_billing_type
     *
     * @return int
     */
    public function getLoadBalancerBillingType()
    {
        return $this->container['load_balancer_billing_type'];
    }

    /**
     * Sets load_balancer_billing_type
     *
     * @param int $load_balancer_billing_type load_balancer_billing_type
     *
     * @return $this
     */
    public function setLoadBalancerBillingType($load_balancer_billing_type)
    {
        $this->container['load_balancer_billing_type'] = $load_balancer_billing_type;

        return $this;
    }

    /**
     * Gets load_balancer_edition
     *
     * @return string
     */
    public function getLoadBalancerEdition()
    {
        return $this->container['load_balancer_edition'];
    }

    /**
     * Sets load_balancer_edition
     *
     * @param string $load_balancer_edition load_balancer_edition
     *
     * @return $this
     */
    public function setLoadBalancerEdition($load_balancer_edition)
    {
        $this->container['load_balancer_edition'] = $load_balancer_edition;

        return $this;
    }

    /**
     * Gets load_balancer_id
     *
     * @return string
     */
    public function getLoadBalancerId()
    {
        return $this->container['load_balancer_id'];
    }

    /**
     * Sets load_balancer_id
     *
     * @param string $load_balancer_id load_balancer_id
     *
     * @return $this
     */
    public function setLoadBalancerId($load_balancer_id)
    {
        $this->container['load_balancer_id'] = $load_balancer_id;

        return $this;
    }

    /**
     * Gets load_balancer_name
     *
     * @return string
     */
    public function getLoadBalancerName()
    {
        return $this->container['load_balancer_name'];
    }

    /**
     * Sets load_balancer_name
     *
     * @param string $load_balancer_name load_balancer_name
     *
     * @return $this
     */
    public function setLoadBalancerName($load_balancer_name)
    {
        $this->container['load_balancer_name'] = $load_balancer_name;

        return $this;
    }

    /**
     * Gets local_addresses
     *
     * @return string[]
     */
    public function getLocalAddresses()
    {
        return $this->container['local_addresses'];
    }

    /**
     * Sets local_addresses
     *
     * @param string[] $local_addresses local_addresses
     *
     * @return $this
     */
    public function setLocalAddresses($local_addresses)
    {
        $this->container['local_addresses'] = $local_addresses;

        return $this;
    }

    /**
     * Gets lock_reason
     *
     * @return string
     */
    public function getLockReason()
    {
        return $this->container['lock_reason'];
    }

    /**
     * Sets lock_reason
     *
     * @param string $lock_reason lock_reason
     *
     * @return $this
     */
    public function setLockReason($lock_reason)
    {
        $this->container['lock_reason'] = $lock_reason;

        return $this;
    }

    /**
     * Gets modification_protection_reason
     *
     * @return string
     */
    public function getModificationProtectionReason()
    {
        return $this->container['modification_protection_reason'];
    }

    /**
     * Sets modification_protection_reason
     *
     * @param string $modification_protection_reason modification_protection_reason
     *
     * @return $this
     */
    public function setModificationProtectionReason($modification_protection_reason)
    {
        $this->container['modification_protection_reason'] = $modification_protection_reason;

        return $this;
    }

    /**
     * Gets modification_protection_status
     *
     * @return string
     */
    public function getModificationProtectionStatus()
    {
        return $this->container['modification_protection_status'];
    }

    /**
     * Sets modification_protection_status
     *
     * @param string $modification_protection_status modification_protection_status
     *
     * @return $this
     */
    public function setModificationProtectionStatus($modification_protection_status)
    {
        $this->container['modification_protection_status'] = $modification_protection_status;

        return $this;
    }

    /**
     * Gets overdue_time
     *
     * @return string
     */
    public function getOverdueTime()
    {
        return $this->container['overdue_time'];
    }

    /**
     * Sets overdue_time
     *
     * @param string $overdue_time overdue_time
     *
     * @return $this
     */
    public function setOverdueTime($overdue_time)
    {
        $this->container['overdue_time'] = $overdue_time;

        return $this;
    }

    /**
     * Gets project_name
     *
     * @return string
     */
    public function getProjectName()
    {
        return $this->container['project_name'];
    }

    /**
     * Sets project_name
     *
     * @param string $project_name project_name
     *
     * @return $this
     */
    public function setProjectName($project_name)
    {
        $this->container['project_name'] = $project_name;

        return $this;
    }

    /**
     * Gets request_id
     *
     * @return string
     */
    public function getRequestId()
    {
        return $this->container['request_id'];
    }

    /**
     * Sets request_id
     *
     * @param string $request_id request_id
     *
     * @return $this
     */
    public function setRequestId($request_id)
    {
        $this->container['request_id'] = $request_id;

        return $this;
    }

    /**
     * Gets sni_auto_match
     *
     * @return string
     */
    public function getSniAutoMatch()
    {
        return $this->container['sni_auto_match'];
    }

    /**
     * Sets sni_auto_match
     *
     * @param string $sni_auto_match sni_auto_match
     *
     * @return $this
     */
    public function setSniAutoMatch($sni_auto_match)
    {
        $this->container['sni_auto_match'] = $sni_auto_match;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets subnet_id
     *
     * @return string
     */
    public function getSubnetId()
    {
        return $this->container['subnet_id'];
    }

    /**
     * Sets subnet_id
     *
     * @param string $subnet_id subnet_id
     *
     * @return $this
     */
    public function setSubnetId($subnet_id)
    {
        $this->container['subnet_id'] = $subnet_id;

        return $this;
    }

    /**
     * Gets tls_access_log
     *
     * @return \Byteplus\Alb\Model\TLSAccessLogForDescribeLoadBalancerAttributesOutput
     */
    public function getTlsAccessLog()
    {
        return $this->container['tls_access_log'];
    }

    /**
     * Sets tls_access_log
     *
     * @param \Byteplus\Alb\Model\TLSAccessLogForDescribeLoadBalancerAttributesOutput $tls_access_log tls_access_log
     *
     * @return $this
     */
    public function setTlsAccessLog($tls_access_log)
    {
        $this->container['tls_access_log'] = $tls_access_log;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \Byteplus\Alb\Model\TagForDescribeLoadBalancerAttributesOutput[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \Byteplus\Alb\Model\TagForDescribeLoadBalancerAttributesOutput[] $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets update_time
     *
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->container['update_time'];
    }

    /**
     * Sets update_time
     *
     * @param string $update_time update_time
     *
     * @return $this
     */
    public function setUpdateTime($update_time)
    {
        $this->container['update_time'] = $update_time;

        return $this;
    }

    /**
     * Gets vpc_id
     *
     * @return string
     */
    public function getVpcId()
    {
        return $this->container['vpc_id'];
    }

    /**
     * Sets vpc_id
     *
     * @param string $vpc_id vpc_id
     *
     * @return $this
     */
    public function setVpcId($vpc_id)
    {
        $this->container['vpc_id'] = $vpc_id;

        return $this;
    }

    /**
     * Gets waf_instance_id
     *
     * @return string
     */
    public function getWafInstanceId()
    {
        return $this->container['waf_instance_id'];
    }

    /**
     * Sets waf_instance_id
     *
     * @param string $waf_instance_id waf_instance_id
     *
     * @return $this
     */
    public function setWafInstanceId($waf_instance_id)
    {
        $this->container['waf_instance_id'] = $waf_instance_id;

        return $this;
    }

    /**
     * Gets waf_protection_enabled
     *
     * @return string
     */
    public function getWafProtectionEnabled()
    {
        return $this->container['waf_protection_enabled'];
    }

    /**
     * Sets waf_protection_enabled
     *
     * @param string $waf_protection_enabled waf_protection_enabled
     *
     * @return $this
     */
    public function setWafProtectionEnabled($waf_protection_enabled)
    {
        $this->container['waf_protection_enabled'] = $waf_protection_enabled;

        return $this;
    }

    /**
     * Gets zone_mappings
     *
     * @return \Byteplus\Alb\Model\ZoneMappingForDescribeLoadBalancerAttributesOutput[]
     */
    public function getZoneMappings()
    {
        return $this->container['zone_mappings'];
    }

    /**
     * Sets zone_mappings
     *
     * @param \Byteplus\Alb\Model\ZoneMappingForDescribeLoadBalancerAttributesOutput[] $zone_mappings zone_mappings
     *
     * @return $this
     */
    public function setZoneMappings($zone_mappings)
    {
        $this->container['zone_mappings'] = $zone_mappings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

