<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Alb\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class DomainExtensionForDescribeListenerAttributesOutput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DomainExtensionForDescribeListenerAttributesOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'cert_center_certificate_id' => 'string',
        'certificate_id' => 'string',
        'certificate_source' => 'string',
        'domain' => 'string',
        'domain_extension_id' => 'string',
        'listener_id' => 'string',
        'pca_leaf_certificate_id' => 'string',
        'san' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'cert_center_certificate_id' => null,
        'certificate_id' => null,
        'certificate_source' => null,
        'domain' => null,
        'domain_extension_id' => null,
        'listener_id' => null,
        'pca_leaf_certificate_id' => null,
        'san' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cert_center_certificate_id' => 'CertCenterCertificateId',
        'certificate_id' => 'CertificateId',
        'certificate_source' => 'CertificateSource',
        'domain' => 'Domain',
        'domain_extension_id' => 'DomainExtensionId',
        'listener_id' => 'ListenerId',
        'pca_leaf_certificate_id' => 'PcaLeafCertificateId',
        'san' => 'San'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cert_center_certificate_id' => 'setCertCenterCertificateId',
        'certificate_id' => 'setCertificateId',
        'certificate_source' => 'setCertificateSource',
        'domain' => 'setDomain',
        'domain_extension_id' => 'setDomainExtensionId',
        'listener_id' => 'setListenerId',
        'pca_leaf_certificate_id' => 'setPcaLeafCertificateId',
        'san' => 'setSan'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cert_center_certificate_id' => 'getCertCenterCertificateId',
        'certificate_id' => 'getCertificateId',
        'certificate_source' => 'getCertificateSource',
        'domain' => 'getDomain',
        'domain_extension_id' => 'getDomainExtensionId',
        'listener_id' => 'getListenerId',
        'pca_leaf_certificate_id' => 'getPcaLeafCertificateId',
        'san' => 'getSan'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['cert_center_certificate_id'] = isset($data['cert_center_certificate_id']) ? $data['cert_center_certificate_id'] : null;
        $this->container['certificate_id'] = isset($data['certificate_id']) ? $data['certificate_id'] : null;
        $this->container['certificate_source'] = isset($data['certificate_source']) ? $data['certificate_source'] : null;
        $this->container['domain'] = isset($data['domain']) ? $data['domain'] : null;
        $this->container['domain_extension_id'] = isset($data['domain_extension_id']) ? $data['domain_extension_id'] : null;
        $this->container['listener_id'] = isset($data['listener_id']) ? $data['listener_id'] : null;
        $this->container['pca_leaf_certificate_id'] = isset($data['pca_leaf_certificate_id']) ? $data['pca_leaf_certificate_id'] : null;
        $this->container['san'] = isset($data['san']) ? $data['san'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cert_center_certificate_id
     *
     * @return string
     */
    public function getCertCenterCertificateId()
    {
        return $this->container['cert_center_certificate_id'];
    }

    /**
     * Sets cert_center_certificate_id
     *
     * @param string $cert_center_certificate_id cert_center_certificate_id
     *
     * @return $this
     */
    public function setCertCenterCertificateId($cert_center_certificate_id)
    {
        $this->container['cert_center_certificate_id'] = $cert_center_certificate_id;

        return $this;
    }

    /**
     * Gets certificate_id
     *
     * @return string
     */
    public function getCertificateId()
    {
        return $this->container['certificate_id'];
    }

    /**
     * Sets certificate_id
     *
     * @param string $certificate_id certificate_id
     *
     * @return $this
     */
    public function setCertificateId($certificate_id)
    {
        $this->container['certificate_id'] = $certificate_id;

        return $this;
    }

    /**
     * Gets certificate_source
     *
     * @return string
     */
    public function getCertificateSource()
    {
        return $this->container['certificate_source'];
    }

    /**
     * Sets certificate_source
     *
     * @param string $certificate_source certificate_source
     *
     * @return $this
     */
    public function setCertificateSource($certificate_source)
    {
        $this->container['certificate_source'] = $certificate_source;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain domain
     *
     * @return $this
     */
    public function setDomain($domain)
    {
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets domain_extension_id
     *
     * @return string
     */
    public function getDomainExtensionId()
    {
        return $this->container['domain_extension_id'];
    }

    /**
     * Sets domain_extension_id
     *
     * @param string $domain_extension_id domain_extension_id
     *
     * @return $this
     */
    public function setDomainExtensionId($domain_extension_id)
    {
        $this->container['domain_extension_id'] = $domain_extension_id;

        return $this;
    }

    /**
     * Gets listener_id
     *
     * @return string
     */
    public function getListenerId()
    {
        return $this->container['listener_id'];
    }

    /**
     * Sets listener_id
     *
     * @param string $listener_id listener_id
     *
     * @return $this
     */
    public function setListenerId($listener_id)
    {
        $this->container['listener_id'] = $listener_id;

        return $this;
    }

    /**
     * Gets pca_leaf_certificate_id
     *
     * @return string
     */
    public function getPcaLeafCertificateId()
    {
        return $this->container['pca_leaf_certificate_id'];
    }

    /**
     * Sets pca_leaf_certificate_id
     *
     * @param string $pca_leaf_certificate_id pca_leaf_certificate_id
     *
     * @return $this
     */
    public function setPcaLeafCertificateId($pca_leaf_certificate_id)
    {
        $this->container['pca_leaf_certificate_id'] = $pca_leaf_certificate_id;

        return $this;
    }

    /**
     * Gets san
     *
     * @return string
     */
    public function getSan()
    {
        return $this->container['san'];
    }

    /**
     * Sets san
     *
     * @param string $san san
     *
     * @return $this
     */
    public function setSan($san)
    {
        $this->container['san'] = $san;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

