<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Byteplus\Alb\Model;

use ArrayAccess;
use Byteplus\Common\ObjectSerializer;
use Byteplus\Common\ModelInterface;

class ServerGroupForDescribeServerGroupsOutput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ServerGroupForDescribeServerGroupsOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'create_time' => 'string',
        'cross_zone_enabled' => 'string',
        'description' => 'string',
        'health_check' => '\Byteplus\Alb\Model\HealthCheckForDescribeServerGroupsOutput',
        'ip_address_type' => 'string',
        'listeners' => 'string[]',
        'project_name' => 'string',
        'protocol' => 'string',
        'scheduler' => 'string',
        'server_count' => 'int',
        'server_group_id' => 'string',
        'server_group_name' => 'string',
        'server_group_type' => 'string',
        'status' => 'string',
        'sticky_session_config' => '\Byteplus\Alb\Model\StickySessionConfigForDescribeServerGroupsOutput',
        'tags' => '\Byteplus\Alb\Model\TagForDescribeServerGroupsOutput[]',
        'update_time' => 'string',
        'vpc_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'create_time' => null,
        'cross_zone_enabled' => null,
        'description' => null,
        'health_check' => null,
        'ip_address_type' => null,
        'listeners' => null,
        'project_name' => null,
        'protocol' => null,
        'scheduler' => null,
        'server_count' => null,
        'server_group_id' => null,
        'server_group_name' => null,
        'server_group_type' => null,
        'status' => null,
        'sticky_session_config' => null,
        'tags' => null,
        'update_time' => null,
        'vpc_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'create_time' => 'CreateTime',
        'cross_zone_enabled' => 'CrossZoneEnabled',
        'description' => 'Description',
        'health_check' => 'HealthCheck',
        'ip_address_type' => 'IPAddressType',
        'listeners' => 'Listeners',
        'project_name' => 'ProjectName',
        'protocol' => 'Protocol',
        'scheduler' => 'Scheduler',
        'server_count' => 'ServerCount',
        'server_group_id' => 'ServerGroupId',
        'server_group_name' => 'ServerGroupName',
        'server_group_type' => 'ServerGroupType',
        'status' => 'Status',
        'sticky_session_config' => 'StickySessionConfig',
        'tags' => 'Tags',
        'update_time' => 'UpdateTime',
        'vpc_id' => 'VpcId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'create_time' => 'setCreateTime',
        'cross_zone_enabled' => 'setCrossZoneEnabled',
        'description' => 'setDescription',
        'health_check' => 'setHealthCheck',
        'ip_address_type' => 'setIpAddressType',
        'listeners' => 'setListeners',
        'project_name' => 'setProjectName',
        'protocol' => 'setProtocol',
        'scheduler' => 'setScheduler',
        'server_count' => 'setServerCount',
        'server_group_id' => 'setServerGroupId',
        'server_group_name' => 'setServerGroupName',
        'server_group_type' => 'setServerGroupType',
        'status' => 'setStatus',
        'sticky_session_config' => 'setStickySessionConfig',
        'tags' => 'setTags',
        'update_time' => 'setUpdateTime',
        'vpc_id' => 'setVpcId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'create_time' => 'getCreateTime',
        'cross_zone_enabled' => 'getCrossZoneEnabled',
        'description' => 'getDescription',
        'health_check' => 'getHealthCheck',
        'ip_address_type' => 'getIpAddressType',
        'listeners' => 'getListeners',
        'project_name' => 'getProjectName',
        'protocol' => 'getProtocol',
        'scheduler' => 'getScheduler',
        'server_count' => 'getServerCount',
        'server_group_id' => 'getServerGroupId',
        'server_group_name' => 'getServerGroupName',
        'server_group_type' => 'getServerGroupType',
        'status' => 'getStatus',
        'sticky_session_config' => 'getStickySessionConfig',
        'tags' => 'getTags',
        'update_time' => 'getUpdateTime',
        'vpc_id' => 'getVpcId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['create_time'] = isset($data['create_time']) ? $data['create_time'] : null;
        $this->container['cross_zone_enabled'] = isset($data['cross_zone_enabled']) ? $data['cross_zone_enabled'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['health_check'] = isset($data['health_check']) ? $data['health_check'] : null;
        $this->container['ip_address_type'] = isset($data['ip_address_type']) ? $data['ip_address_type'] : null;
        $this->container['listeners'] = isset($data['listeners']) ? $data['listeners'] : null;
        $this->container['project_name'] = isset($data['project_name']) ? $data['project_name'] : null;
        $this->container['protocol'] = isset($data['protocol']) ? $data['protocol'] : null;
        $this->container['scheduler'] = isset($data['scheduler']) ? $data['scheduler'] : null;
        $this->container['server_count'] = isset($data['server_count']) ? $data['server_count'] : null;
        $this->container['server_group_id'] = isset($data['server_group_id']) ? $data['server_group_id'] : null;
        $this->container['server_group_name'] = isset($data['server_group_name']) ? $data['server_group_name'] : null;
        $this->container['server_group_type'] = isset($data['server_group_type']) ? $data['server_group_type'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['sticky_session_config'] = isset($data['sticky_session_config']) ? $data['sticky_session_config'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['update_time'] = isset($data['update_time']) ? $data['update_time'] : null;
        $this->container['vpc_id'] = isset($data['vpc_id']) ? $data['vpc_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets create_time
     *
     * @return string
     */
    public function getCreateTime()
    {
        return $this->container['create_time'];
    }

    /**
     * Sets create_time
     *
     * @param string $create_time create_time
     *
     * @return $this
     */
    public function setCreateTime($create_time)
    {
        $this->container['create_time'] = $create_time;

        return $this;
    }

    /**
     * Gets cross_zone_enabled
     *
     * @return string
     */
    public function getCrossZoneEnabled()
    {
        return $this->container['cross_zone_enabled'];
    }

    /**
     * Sets cross_zone_enabled
     *
     * @param string $cross_zone_enabled cross_zone_enabled
     *
     * @return $this
     */
    public function setCrossZoneEnabled($cross_zone_enabled)
    {
        $this->container['cross_zone_enabled'] = $cross_zone_enabled;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets health_check
     *
     * @return \Byteplus\Alb\Model\HealthCheckForDescribeServerGroupsOutput
     */
    public function getHealthCheck()
    {
        return $this->container['health_check'];
    }

    /**
     * Sets health_check
     *
     * @param \Byteplus\Alb\Model\HealthCheckForDescribeServerGroupsOutput $health_check health_check
     *
     * @return $this
     */
    public function setHealthCheck($health_check)
    {
        $this->container['health_check'] = $health_check;

        return $this;
    }

    /**
     * Gets ip_address_type
     *
     * @return string
     */
    public function getIpAddressType()
    {
        return $this->container['ip_address_type'];
    }

    /**
     * Sets ip_address_type
     *
     * @param string $ip_address_type ip_address_type
     *
     * @return $this
     */
    public function setIpAddressType($ip_address_type)
    {
        $this->container['ip_address_type'] = $ip_address_type;

        return $this;
    }

    /**
     * Gets listeners
     *
     * @return string[]
     */
    public function getListeners()
    {
        return $this->container['listeners'];
    }

    /**
     * Sets listeners
     *
     * @param string[] $listeners listeners
     *
     * @return $this
     */
    public function setListeners($listeners)
    {
        $this->container['listeners'] = $listeners;

        return $this;
    }

    /**
     * Gets project_name
     *
     * @return string
     */
    public function getProjectName()
    {
        return $this->container['project_name'];
    }

    /**
     * Sets project_name
     *
     * @param string $project_name project_name
     *
     * @return $this
     */
    public function setProjectName($project_name)
    {
        $this->container['project_name'] = $project_name;

        return $this;
    }

    /**
     * Gets protocol
     *
     * @return string
     */
    public function getProtocol()
    {
        return $this->container['protocol'];
    }

    /**
     * Sets protocol
     *
     * @param string $protocol protocol
     *
     * @return $this
     */
    public function setProtocol($protocol)
    {
        $this->container['protocol'] = $protocol;

        return $this;
    }

    /**
     * Gets scheduler
     *
     * @return string
     */
    public function getScheduler()
    {
        return $this->container['scheduler'];
    }

    /**
     * Sets scheduler
     *
     * @param string $scheduler scheduler
     *
     * @return $this
     */
    public function setScheduler($scheduler)
    {
        $this->container['scheduler'] = $scheduler;

        return $this;
    }

    /**
     * Gets server_count
     *
     * @return int
     */
    public function getServerCount()
    {
        return $this->container['server_count'];
    }

    /**
     * Sets server_count
     *
     * @param int $server_count server_count
     *
     * @return $this
     */
    public function setServerCount($server_count)
    {
        $this->container['server_count'] = $server_count;

        return $this;
    }

    /**
     * Gets server_group_id
     *
     * @return string
     */
    public function getServerGroupId()
    {
        return $this->container['server_group_id'];
    }

    /**
     * Sets server_group_id
     *
     * @param string $server_group_id server_group_id
     *
     * @return $this
     */
    public function setServerGroupId($server_group_id)
    {
        $this->container['server_group_id'] = $server_group_id;

        return $this;
    }

    /**
     * Gets server_group_name
     *
     * @return string
     */
    public function getServerGroupName()
    {
        return $this->container['server_group_name'];
    }

    /**
     * Sets server_group_name
     *
     * @param string $server_group_name server_group_name
     *
     * @return $this
     */
    public function setServerGroupName($server_group_name)
    {
        $this->container['server_group_name'] = $server_group_name;

        return $this;
    }

    /**
     * Gets server_group_type
     *
     * @return string
     */
    public function getServerGroupType()
    {
        return $this->container['server_group_type'];
    }

    /**
     * Sets server_group_type
     *
     * @param string $server_group_type server_group_type
     *
     * @return $this
     */
    public function setServerGroupType($server_group_type)
    {
        $this->container['server_group_type'] = $server_group_type;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets sticky_session_config
     *
     * @return \Byteplus\Alb\Model\StickySessionConfigForDescribeServerGroupsOutput
     */
    public function getStickySessionConfig()
    {
        return $this->container['sticky_session_config'];
    }

    /**
     * Sets sticky_session_config
     *
     * @param \Byteplus\Alb\Model\StickySessionConfigForDescribeServerGroupsOutput $sticky_session_config sticky_session_config
     *
     * @return $this
     */
    public function setStickySessionConfig($sticky_session_config)
    {
        $this->container['sticky_session_config'] = $sticky_session_config;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \Byteplus\Alb\Model\TagForDescribeServerGroupsOutput[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \Byteplus\Alb\Model\TagForDescribeServerGroupsOutput[] $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets update_time
     *
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->container['update_time'];
    }

    /**
     * Sets update_time
     *
     * @param string $update_time update_time
     *
     * @return $this
     */
    public function setUpdateTime($update_time)
    {
        $this->container['update_time'] = $update_time;

        return $this;
    }

    /**
     * Gets vpc_id
     *
     * @return string
     */
    public function getVpcId()
    {
        return $this->container['vpc_id'];
    }

    /**
     * Sets vpc_id
     *
     * @param string $vpc_id vpc_id
     *
     * @return $this
     */
    public function setVpcId($vpc_id)
    {
        $this->container['vpc_id'] = $vpc_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

